/**
 * @file      
 * @brief     Wrap around OpenGL types, constants and functions.
 * @details   ...
 * @author    ArthurTheDigital (arthurthedigital@gmail.com)
 * @copyright GPL v3.
 * @since     $Id: $ */

#include <ATD/Graphics/Gl.hpp>

#include <ATD/Core/Debug.hpp>

#include <GL/gl.h>
#include <GL/glx.h>

#include <stdio.h>

#include <string>
#include <vector>


/* ATD::Gl aux: */

typedef void (*GlFunc)();

static GlFunc _loadFunction(const char *procName, 
		std::vector<std::string> &failures)
{
	void (*result)() = 
		glXGetProcAddress(reinterpret_cast<const GLubyte *>(procName));
	if (!result) {
		failures.push_back(std::string(procName));
	}
	return result;
}


/* ATD::Gl constants: */

/* Boolean values: */
const ATD::Gl::Boolean ATD::Gl::FALSE = GL_FALSE;
const ATD::Gl::Boolean ATD::Gl::TRUE = GL_TRUE;

/* Data types: */
const ATD::Gl::Enum ATD::Gl::BYTE = GL_BYTE;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_BYTE = GL_UNSIGNED_BYTE;
const ATD::Gl::Enum ATD::Gl::SHORT = GL_SHORT;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_SHORT = GL_UNSIGNED_SHORT;
const ATD::Gl::Enum ATD::Gl::INT = GL_INT;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT = GL_UNSIGNED_INT;
const ATD::Gl::Enum ATD::Gl::FLOAT = GL_FLOAT;
const ATD::Gl::Enum ATD::Gl::M_2_BYTES = GL_2_BYTES;
const ATD::Gl::Enum ATD::Gl::M_3_BYTES = GL_3_BYTES;
const ATD::Gl::Enum ATD::Gl::M_4_BYTES = GL_4_BYTES;
const ATD::Gl::Enum ATD::Gl::DOUBLE = GL_DOUBLE;

/* Primitives: */
const ATD::Gl::Enum ATD::Gl::POINTS = GL_POINTS;
const ATD::Gl::Enum ATD::Gl::LINES = GL_LINES;
const ATD::Gl::Enum ATD::Gl::LINE_LOOP = GL_LINE_LOOP;
const ATD::Gl::Enum ATD::Gl::LINE_STRIP = GL_LINE_STRIP;
const ATD::Gl::Enum ATD::Gl::TRIANGLES = GL_TRIANGLES;
const ATD::Gl::Enum ATD::Gl::TRIANGLE_STRIP = GL_TRIANGLE_STRIP;
const ATD::Gl::Enum ATD::Gl::TRIANGLE_FAN = GL_TRIANGLE_FAN;
const ATD::Gl::Enum ATD::Gl::QUADS = GL_QUADS;
const ATD::Gl::Enum ATD::Gl::QUAD_STRIP = GL_QUAD_STRIP;
const ATD::Gl::Enum ATD::Gl::POLYGON = GL_POLYGON;

/* Vertex arrays: */
const ATD::Gl::Enum ATD::Gl::VERTEX_ARRAY = GL_VERTEX_ARRAY;
const ATD::Gl::Enum ATD::Gl::NORMAL_ARRAY = GL_NORMAL_ARRAY;
const ATD::Gl::Enum ATD::Gl::COLOR_ARRAY = GL_COLOR_ARRAY;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COORD_ARRAY = GL_TEXTURE_COORD_ARRAY;
const ATD::Gl::Enum ATD::Gl::EDGE_FLAG_ARRAY = GL_EDGE_FLAG_ARRAY;
const ATD::Gl::Enum ATD::Gl::VERTEX_ARRAY_SIZE = GL_VERTEX_ARRAY_SIZE;
const ATD::Gl::Enum ATD::Gl::VERTEX_ARRAY_TYPE = GL_VERTEX_ARRAY_TYPE;
const ATD::Gl::Enum ATD::Gl::VERTEX_ARRAY_STRIDE = GL_VERTEX_ARRAY_STRIDE;
const ATD::Gl::Enum ATD::Gl::NORMAL_ARRAY_TYPE = GL_NORMAL_ARRAY_TYPE;
const ATD::Gl::Enum ATD::Gl::NORMAL_ARRAY_STRIDE = GL_NORMAL_ARRAY_STRIDE;
const ATD::Gl::Enum ATD::Gl::COLOR_ARRAY_SIZE = GL_COLOR_ARRAY_SIZE;
const ATD::Gl::Enum ATD::Gl::COLOR_ARRAY_TYPE = GL_COLOR_ARRAY_TYPE;
const ATD::Gl::Enum ATD::Gl::COLOR_ARRAY_STRIDE = GL_COLOR_ARRAY_STRIDE;
const ATD::Gl::Enum ATD::Gl::INDEX_ARRAY_TYPE = GL_INDEX_ARRAY_TYPE;
const ATD::Gl::Enum ATD::Gl::INDEX_ARRAY_STRIDE = GL_INDEX_ARRAY_STRIDE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COORD_ARRAY_SIZE = 
	GL_TEXTURE_COORD_ARRAY_SIZE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COORD_ARRAY_TYPE = 
	GL_TEXTURE_COORD_ARRAY_TYPE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COORD_ARRAY_STRIDE = 
	GL_TEXTURE_COORD_ARRAY_STRIDE;
const ATD::Gl::Enum ATD::Gl::EDGE_FLAG_ARRAY_STRIDE = 
	GL_EDGE_FLAG_ARRAY_STRIDE;
const ATD::Gl::Enum ATD::Gl::VERTEX_ARRAY_POINTER = GL_VERTEX_ARRAY_POINTER;
const ATD::Gl::Enum ATD::Gl::NORMAL_ARRAY_POINTER = GL_NORMAL_ARRAY_POINTER;
const ATD::Gl::Enum ATD::Gl::COLOR_ARRAY_POINTER = GL_COLOR_ARRAY_POINTER;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COORD_ARRAY_POINTER = 
	GL_TEXTURE_COORD_ARRAY_POINTER;
const ATD::Gl::Enum ATD::Gl::EDGE_FLAG_ARRAY_POINTER = 
	GL_EDGE_FLAG_ARRAY_POINTER;
const ATD::Gl::Enum ATD::Gl::V2F = GL_V2F;
const ATD::Gl::Enum ATD::Gl::V3F = GL_V3F;
const ATD::Gl::Enum ATD::Gl::C4UB_V2F = GL_C4UB_V2F;
const ATD::Gl::Enum ATD::Gl::C4UB_V3F = GL_C4UB_V3F;
const ATD::Gl::Enum ATD::Gl::C3F_V3F = GL_C3F_V3F;
const ATD::Gl::Enum ATD::Gl::N3F_V3F = GL_N3F_V3F;
const ATD::Gl::Enum ATD::Gl::C4F_N3F_V3F = GL_C4F_N3F_V3F;
const ATD::Gl::Enum ATD::Gl::T2F_V3F = GL_T2F_V3F;
const ATD::Gl::Enum ATD::Gl::T4F_V4F = GL_T4F_V4F;
const ATD::Gl::Enum ATD::Gl::T2F_C4UB_V3F = GL_T2F_C4UB_V3F;
const ATD::Gl::Enum ATD::Gl::T2F_C3F_V3F = GL_T2F_C3F_V3F;
const ATD::Gl::Enum ATD::Gl::T2F_N3F_V3F = GL_T2F_N3F_V3F;
const ATD::Gl::Enum ATD::Gl::T2F_C4F_N3F_V3F = GL_T2F_C4F_N3F_V3F;
const ATD::Gl::Enum ATD::Gl::T4F_C4F_N3F_V4F = GL_T4F_C4F_N3F_V4F;

/* Matrix Mode */
const ATD::Gl::Enum ATD::Gl::MATRIX_MODE = GL_MATRIX_MODE;
const ATD::Gl::Enum ATD::Gl::MODELVIEW = GL_MODELVIEW;
const ATD::Gl::Enum ATD::Gl::PROJECTION = GL_PROJECTION;
const ATD::Gl::Enum ATD::Gl::TEXTURE = GL_TEXTURE;

/* Points */
const ATD::Gl::Enum ATD::Gl::POINT_SMOOTH = GL_POINT_SMOOTH;
const ATD::Gl::Enum ATD::Gl::POINT_SIZE = GL_POINT_SIZE;
const ATD::Gl::Enum ATD::Gl::POINT_SIZE_GRANULARITY = 
	GL_POINT_SIZE_GRANULARITY;
const ATD::Gl::Enum ATD::Gl::POINT_SIZE_RANGE = GL_POINT_SIZE_RANGE;

/* Lines */
const ATD::Gl::Enum ATD::Gl::LINE_SMOOTH = GL_LINE_SMOOTH;
const ATD::Gl::Enum ATD::Gl::LINE_STIPPLE = GL_LINE_STIPPLE;
const ATD::Gl::Enum ATD::Gl::LINE_STIPPLE_PATTERN = GL_LINE_STIPPLE_PATTERN;
const ATD::Gl::Enum ATD::Gl::LINE_STIPPLE_REPEAT = GL_LINE_STIPPLE_REPEAT;
const ATD::Gl::Enum ATD::Gl::LINE_WIDTH = GL_LINE_WIDTH;
const ATD::Gl::Enum ATD::Gl::LINE_WIDTH_GRANULARITY = 
	GL_LINE_WIDTH_GRANULARITY;
const ATD::Gl::Enum ATD::Gl::LINE_WIDTH_RANGE = GL_LINE_WIDTH_RANGE;

/* Polygons */
const ATD::Gl::Enum ATD::Gl::POINT = GL_POINT;
const ATD::Gl::Enum ATD::Gl::LINE = GL_LINE;
const ATD::Gl::Enum ATD::Gl::FILL = GL_FILL;
const ATD::Gl::Enum ATD::Gl::CW = GL_CW;
const ATD::Gl::Enum ATD::Gl::CCW = GL_CCW;
const ATD::Gl::Enum ATD::Gl::FRONT = GL_FRONT;
const ATD::Gl::Enum ATD::Gl::BACK = GL_BACK;
const ATD::Gl::Enum ATD::Gl::POLYGON_MODE = GL_POLYGON_MODE;
const ATD::Gl::Enum ATD::Gl::POLYGON_SMOOTH = GL_POLYGON_SMOOTH;
const ATD::Gl::Enum ATD::Gl::POLYGON_STIPPLE = GL_POLYGON_STIPPLE;
const ATD::Gl::Enum ATD::Gl::EDGE_FLAG = GL_EDGE_FLAG;
const ATD::Gl::Enum ATD::Gl::CULL_FACE = GL_CULL_FACE;
const ATD::Gl::Enum ATD::Gl::CULL_FACE_MODE = GL_CULL_FACE_MODE;
const ATD::Gl::Enum ATD::Gl::FRONT_FACE = GL_FRONT_FACE;
const ATD::Gl::Enum ATD::Gl::POLYGON_OFFSET_FACTOR = GL_POLYGON_OFFSET_FACTOR;
const ATD::Gl::Enum ATD::Gl::POLYGON_OFFSET_UNITS = GL_POLYGON_OFFSET_UNITS;
const ATD::Gl::Enum ATD::Gl::POLYGON_OFFSET_POINT = GL_POLYGON_OFFSET_POINT;
const ATD::Gl::Enum ATD::Gl::POLYGON_OFFSET_LINE = GL_POLYGON_OFFSET_LINE;
const ATD::Gl::Enum ATD::Gl::POLYGON_OFFSET_FILL = GL_POLYGON_OFFSET_FILL;

/* Display Lists */
const ATD::Gl::Enum ATD::Gl::COMPILE = GL_COMPILE;
const ATD::Gl::Enum ATD::Gl::COMPILE_AND_EXECUTE = GL_COMPILE_AND_EXECUTE;
const ATD::Gl::Enum ATD::Gl::LIST_BASE = GL_LIST_BASE;
const ATD::Gl::Enum ATD::Gl::LIST_INDEX = GL_LIST_INDEX;
const ATD::Gl::Enum ATD::Gl::LIST_MODE = GL_LIST_MODE;

/* Depth buffer */
const ATD::Gl::Enum ATD::Gl::NEVER = GL_NEVER;
const ATD::Gl::Enum ATD::Gl::LESS = GL_LESS;
const ATD::Gl::Enum ATD::Gl::EQUAL = GL_EQUAL;
const ATD::Gl::Enum ATD::Gl::LEQUAL = GL_LEQUAL;
const ATD::Gl::Enum ATD::Gl::GREATER = GL_GREATER;
const ATD::Gl::Enum ATD::Gl::NOTEQUAL = GL_NOTEQUAL;
const ATD::Gl::Enum ATD::Gl::GEQUAL = GL_GEQUAL;
const ATD::Gl::Enum ATD::Gl::ALWAYS = GL_ALWAYS;
const ATD::Gl::Enum ATD::Gl::DEPTH_TEST = GL_DEPTH_TEST;
const ATD::Gl::Enum ATD::Gl::DEPTH_BITS = GL_DEPTH_BITS;
const ATD::Gl::Enum ATD::Gl::DEPTH_CLEAR_VALUE = GL_DEPTH_CLEAR_VALUE;
const ATD::Gl::Enum ATD::Gl::DEPTH_FUNC = GL_DEPTH_FUNC;
const ATD::Gl::Enum ATD::Gl::DEPTH_RANGE = GL_DEPTH_RANGE;
const ATD::Gl::Enum ATD::Gl::DEPTH_WRITEMASK = GL_DEPTH_WRITEMASK;
const ATD::Gl::Enum ATD::Gl::DEPTH_COMPONENT = GL_DEPTH_COMPONENT;

/* Lighting */
const ATD::Gl::Enum ATD::Gl::LIGHTING = GL_LIGHTING;
const ATD::Gl::Enum ATD::Gl::LIGHT0 = GL_LIGHT0;
const ATD::Gl::Enum ATD::Gl::LIGHT1 = GL_LIGHT1;
const ATD::Gl::Enum ATD::Gl::LIGHT2 = GL_LIGHT2;
const ATD::Gl::Enum ATD::Gl::LIGHT3 = GL_LIGHT3;
const ATD::Gl::Enum ATD::Gl::LIGHT4 = GL_LIGHT4;
const ATD::Gl::Enum ATD::Gl::LIGHT5 = GL_LIGHT5;
const ATD::Gl::Enum ATD::Gl::LIGHT6 = GL_LIGHT6;
const ATD::Gl::Enum ATD::Gl::LIGHT7 = GL_LIGHT7;
const ATD::Gl::Enum ATD::Gl::SPOT_EXPONENT = GL_SPOT_EXPONENT;
const ATD::Gl::Enum ATD::Gl::SPOT_CUTOFF = GL_SPOT_CUTOFF;
const ATD::Gl::Enum ATD::Gl::CONSTANT_ATTENUATION = GL_CONSTANT_ATTENUATION;
const ATD::Gl::Enum ATD::Gl::LINEAR_ATTENUATION = GL_LINEAR_ATTENUATION;
const ATD::Gl::Enum ATD::Gl::QUADRATIC_ATTENUATION = GL_QUADRATIC_ATTENUATION;
const ATD::Gl::Enum ATD::Gl::AMBIENT = GL_AMBIENT;
const ATD::Gl::Enum ATD::Gl::DIFFUSE = GL_DIFFUSE;
const ATD::Gl::Enum ATD::Gl::SPECULAR = GL_SPECULAR;
const ATD::Gl::Enum ATD::Gl::SHININESS = GL_SHININESS;
const ATD::Gl::Enum ATD::Gl::EMISSION = GL_EMISSION;
const ATD::Gl::Enum ATD::Gl::POSITION = GL_POSITION;
const ATD::Gl::Enum ATD::Gl::SPOT_DIRECTION = GL_SPOT_DIRECTION;
const ATD::Gl::Enum ATD::Gl::AMBIENT_AND_DIFFUSE = GL_AMBIENT_AND_DIFFUSE;
const ATD::Gl::Enum ATD::Gl::COLOR_INDEXES = GL_COLOR_INDEXES;
const ATD::Gl::Enum ATD::Gl::LIGHT_MODEL_TWO_SIDE = GL_LIGHT_MODEL_TWO_SIDE;
const ATD::Gl::Enum ATD::Gl::LIGHT_MODEL_LOCAL_VIEWER = 
	GL_LIGHT_MODEL_LOCAL_VIEWER;
const ATD::Gl::Enum ATD::Gl::LIGHT_MODEL_AMBIENT = GL_LIGHT_MODEL_AMBIENT;
const ATD::Gl::Enum ATD::Gl::FRONT_AND_BACK = GL_FRONT_AND_BACK;
const ATD::Gl::Enum ATD::Gl::SHADE_MODEL = GL_SHADE_MODEL;
const ATD::Gl::Enum ATD::Gl::FLAT = GL_FLAT;
const ATD::Gl::Enum ATD::Gl::SMOOTH = GL_SMOOTH;
const ATD::Gl::Enum ATD::Gl::COLOR_MATERIAL = GL_COLOR_MATERIAL;
const ATD::Gl::Enum ATD::Gl::COLOR_MATERIAL_FACE = GL_COLOR_MATERIAL_FACE;
const ATD::Gl::Enum ATD::Gl::COLOR_MATERIAL_PARAMETER = 
	GL_COLOR_MATERIAL_PARAMETER;
const ATD::Gl::Enum ATD::Gl::NORMALIZE = GL_NORMALIZE;

/* User clipping planes */
const ATD::Gl::Enum ATD::Gl::CLIP_PLANE0 = GL_CLIP_PLANE0;
const ATD::Gl::Enum ATD::Gl::CLIP_PLANE1 = GL_CLIP_PLANE1;
const ATD::Gl::Enum ATD::Gl::CLIP_PLANE2 = GL_CLIP_PLANE2;
const ATD::Gl::Enum ATD::Gl::CLIP_PLANE3 = GL_CLIP_PLANE3;
const ATD::Gl::Enum ATD::Gl::CLIP_PLANE4 = GL_CLIP_PLANE4;
const ATD::Gl::Enum ATD::Gl::CLIP_PLANE5 = GL_CLIP_PLANE5;

/* Accumulation buffer */
const ATD::Gl::Enum ATD::Gl::ACCUM_RED_BITS = GL_ACCUM_RED_BITS;
const ATD::Gl::Enum ATD::Gl::ACCUM_GREEN_BITS = GL_ACCUM_GREEN_BITS;
const ATD::Gl::Enum ATD::Gl::ACCUM_BLUE_BITS = GL_ACCUM_BLUE_BITS;
const ATD::Gl::Enum ATD::Gl::ACCUM_ALPHA_BITS = GL_ACCUM_ALPHA_BITS;
const ATD::Gl::Enum ATD::Gl::ACCUM_CLEAR_VALUE = GL_ACCUM_CLEAR_VALUE;
const ATD::Gl::Enum ATD::Gl::ACCUM = GL_ACCUM;
const ATD::Gl::Enum ATD::Gl::ADD = GL_ADD;
const ATD::Gl::Enum ATD::Gl::LOAD = GL_LOAD;
const ATD::Gl::Enum ATD::Gl::MULT = GL_MULT;
const ATD::Gl::Enum ATD::Gl::RETURN = GL_RETURN;

/* Alpha testing */
const ATD::Gl::Enum ATD::Gl::ALPHA_TEST = GL_ALPHA_TEST;
const ATD::Gl::Enum ATD::Gl::ALPHA_TEST_REF = GL_ALPHA_TEST_REF;
const ATD::Gl::Enum ATD::Gl::ALPHA_TEST_FUNC = GL_ALPHA_TEST_FUNC;

/* Blending */
const ATD::Gl::Enum ATD::Gl::BLEND = GL_BLEND;
const ATD::Gl::Enum ATD::Gl::BLEND_SRC = GL_BLEND_SRC;
const ATD::Gl::Enum ATD::Gl::BLEND_DST = GL_BLEND_DST;
const ATD::Gl::Enum ATD::Gl::ZERO = GL_ZERO;
const ATD::Gl::Enum ATD::Gl::ONE = GL_ONE;
const ATD::Gl::Enum ATD::Gl::SRC_COLOR = GL_SRC_COLOR;
const ATD::Gl::Enum ATD::Gl::ONE_MINUS_SRC_COLOR = GL_ONE_MINUS_SRC_COLOR;
const ATD::Gl::Enum ATD::Gl::SRC_ALPHA = GL_SRC_ALPHA;
const ATD::Gl::Enum ATD::Gl::ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA;
const ATD::Gl::Enum ATD::Gl::DST_ALPHA = GL_DST_ALPHA;
const ATD::Gl::Enum ATD::Gl::ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA;
const ATD::Gl::Enum ATD::Gl::DST_COLOR = GL_DST_COLOR;
const ATD::Gl::Enum ATD::Gl::ONE_MINUS_DST_COLOR = GL_ONE_MINUS_DST_COLOR;
const ATD::Gl::Enum ATD::Gl::SRC_ALPHA_SATURATE = GL_SRC_ALPHA_SATURATE;

/* Render Mode */
const ATD::Gl::Enum ATD::Gl::FEEDBACK = GL_FEEDBACK;
const ATD::Gl::Enum ATD::Gl::RENDER = GL_RENDER;
const ATD::Gl::Enum ATD::Gl::SELECT = GL_SELECT;

/* Feedback */
const ATD::Gl::Enum ATD::Gl::M_2D = GL_2D;
const ATD::Gl::Enum ATD::Gl::M_3D = GL_3D;
const ATD::Gl::Enum ATD::Gl::M_3D_COLOR = GL_3D_COLOR;
const ATD::Gl::Enum ATD::Gl::M_3D_COLOR_TEXTURE = GL_3D_COLOR_TEXTURE;
const ATD::Gl::Enum ATD::Gl::M_4D_COLOR_TEXTURE = GL_4D_COLOR_TEXTURE;
const ATD::Gl::Enum ATD::Gl::POINT_TOKEN = GL_POINT_TOKEN;
const ATD::Gl::Enum ATD::Gl::LINE_TOKEN = GL_LINE_TOKEN;
const ATD::Gl::Enum ATD::Gl::LINE_RESET_TOKEN = GL_LINE_RESET_TOKEN;
const ATD::Gl::Enum ATD::Gl::POLYGON_TOKEN = GL_POLYGON_TOKEN;
const ATD::Gl::Enum ATD::Gl::BITMAP_TOKEN = GL_BITMAP_TOKEN;
const ATD::Gl::Enum ATD::Gl::DRAW_PIXEL_TOKEN = GL_DRAW_PIXEL_TOKEN;
const ATD::Gl::Enum ATD::Gl::COPY_PIXEL_TOKEN = GL_COPY_PIXEL_TOKEN;
const ATD::Gl::Enum ATD::Gl::PASS_THROUGH_TOKEN = GL_PASS_THROUGH_TOKEN;
const ATD::Gl::Enum ATD::Gl::FEEDBACK_BUFFER_POINTER = 
	GL_FEEDBACK_BUFFER_POINTER;
const ATD::Gl::Enum ATD::Gl::FEEDBACK_BUFFER_SIZE = GL_FEEDBACK_BUFFER_SIZE;
const ATD::Gl::Enum ATD::Gl::FEEDBACK_BUFFER_TYPE = GL_FEEDBACK_BUFFER_TYPE;

/* Selection */
const ATD::Gl::Enum ATD::Gl::SELECTION_BUFFER_POINTER = 
	GL_SELECTION_BUFFER_POINTER;
const ATD::Gl::Enum ATD::Gl::SELECTION_BUFFER_SIZE = GL_SELECTION_BUFFER_SIZE;

/* Fog */
const ATD::Gl::Enum ATD::Gl::FOG = GL_FOG;
const ATD::Gl::Enum ATD::Gl::FOG_MODE = GL_FOG_MODE;
const ATD::Gl::Enum ATD::Gl::FOG_DENSITY = GL_FOG_DENSITY;
const ATD::Gl::Enum ATD::Gl::FOG_COLOR = GL_FOG_COLOR;
const ATD::Gl::Enum ATD::Gl::FOG_INDEX = GL_FOG_INDEX;
const ATD::Gl::Enum ATD::Gl::FOG_START = GL_FOG_START;
const ATD::Gl::Enum ATD::Gl::FOG_END = GL_FOG_END;
const ATD::Gl::Enum ATD::Gl::LINEAR = GL_LINEAR;
const ATD::Gl::Enum ATD::Gl::EXP = GL_EXP;
const ATD::Gl::Enum ATD::Gl::EXP2 = GL_EXP2;

/* Logic Ops */
const ATD::Gl::Enum ATD::Gl::LOGIC_OP = GL_LOGIC_OP;
const ATD::Gl::Enum ATD::Gl::INDEX_LOGIC_OP = GL_INDEX_LOGIC_OP;
const ATD::Gl::Enum ATD::Gl::COLOR_LOGIC_OP = GL_COLOR_LOGIC_OP;
const ATD::Gl::Enum ATD::Gl::LOGIC_OP_MODE = GL_LOGIC_OP_MODE;
const ATD::Gl::Enum ATD::Gl::CLEAR = GL_CLEAR;
const ATD::Gl::Enum ATD::Gl::SET = GL_SET;
const ATD::Gl::Enum ATD::Gl::COPY = GL_COPY;
const ATD::Gl::Enum ATD::Gl::COPY_INVERTED = GL_COPY_INVERTED;
const ATD::Gl::Enum ATD::Gl::NOOP = GL_NOOP;
const ATD::Gl::Enum ATD::Gl::INVERT = GL_INVERT;
const ATD::Gl::Enum ATD::Gl::AND = GL_AND;
const ATD::Gl::Enum ATD::Gl::NAND = GL_NAND;
const ATD::Gl::Enum ATD::Gl::OR = GL_OR;
const ATD::Gl::Enum ATD::Gl::NOR = GL_NOR;
const ATD::Gl::Enum ATD::Gl::XOR = GL_XOR;
const ATD::Gl::Enum ATD::Gl::EQUIV = GL_EQUIV;
const ATD::Gl::Enum ATD::Gl::AND_REVERSE = GL_AND_REVERSE;
const ATD::Gl::Enum ATD::Gl::AND_INVERTED = GL_AND_INVERTED;
const ATD::Gl::Enum ATD::Gl::OR_REVERSE = GL_OR_REVERSE;
const ATD::Gl::Enum ATD::Gl::OR_INVERTED = GL_OR_INVERTED;

/* Stencil */
const ATD::Gl::Enum ATD::Gl::STENCIL_BITS = GL_STENCIL_BITS;
const ATD::Gl::Enum ATD::Gl::STENCIL_TEST = GL_STENCIL_TEST;
const ATD::Gl::Enum ATD::Gl::STENCIL_CLEAR_VALUE = GL_STENCIL_CLEAR_VALUE;
const ATD::Gl::Enum ATD::Gl::STENCIL_FUNC = GL_STENCIL_FUNC;
const ATD::Gl::Enum ATD::Gl::STENCIL_VALUE_MASK = GL_STENCIL_VALUE_MASK;
const ATD::Gl::Enum ATD::Gl::STENCIL_FAIL = GL_STENCIL_FAIL;
const ATD::Gl::Enum ATD::Gl::STENCIL_PASS_DEPTH_FAIL = 
	GL_STENCIL_PASS_DEPTH_FAIL;
const ATD::Gl::Enum ATD::Gl::STENCIL_PASS_DEPTH_PASS = 
	GL_STENCIL_PASS_DEPTH_PASS;
const ATD::Gl::Enum ATD::Gl::STENCIL_REF = GL_STENCIL_REF;
const ATD::Gl::Enum ATD::Gl::STENCIL_WRITEMASK = GL_STENCIL_WRITEMASK;
const ATD::Gl::Enum ATD::Gl::STENCIL_INDEX = GL_STENCIL_INDEX;
const ATD::Gl::Enum ATD::Gl::KEEP = GL_KEEP;
const ATD::Gl::Enum ATD::Gl::REPLACE = GL_REPLACE;
const ATD::Gl::Enum ATD::Gl::INCR = GL_INCR;
const ATD::Gl::Enum ATD::Gl::DECR = GL_DECR;

/* Buffers, Pixel Drawing/Reading */
const ATD::Gl::Enum ATD::Gl::NONE = GL_NONE;
const ATD::Gl::Enum ATD::Gl::LEFT = GL_LEFT;
const ATD::Gl::Enum ATD::Gl::RIGHT = GL_RIGHT;
/* FRONT; */
/* BACK; */
/* FRONT_AND_BACK; */
const ATD::Gl::Enum ATD::Gl::FRONT_LEFT = GL_FRONT_LEFT;
const ATD::Gl::Enum ATD::Gl::FRONT_RIGHT = GL_FRONT_RIGHT;
const ATD::Gl::Enum ATD::Gl::BACK_LEFT = GL_BACK_LEFT;
const ATD::Gl::Enum ATD::Gl::BACK_RIGHT = GL_BACK_RIGHT;
const ATD::Gl::Enum ATD::Gl::AUX0 = GL_AUX0;
const ATD::Gl::Enum ATD::Gl::AUX1 = GL_AUX1;
const ATD::Gl::Enum ATD::Gl::AUX2 = GL_AUX2;
const ATD::Gl::Enum ATD::Gl::AUX3 = GL_AUX3;
const ATD::Gl::Enum ATD::Gl::COLOR_INDEX = GL_COLOR_INDEX;
const ATD::Gl::Enum ATD::Gl::RED = GL_RED;
const ATD::Gl::Enum ATD::Gl::GREEN = GL_GREEN;;
const ATD::Gl::Enum ATD::Gl::BLUE = GL_BLUE;
const ATD::Gl::Enum ATD::Gl::ALPHA = GL_ALPHA;
const ATD::Gl::Enum ATD::Gl::LUMINANCE = GL_LUMINANCE;
const ATD::Gl::Enum ATD::Gl::LUMINANCE_ALPHA = GL_LUMINANCE_ALPHA;
const ATD::Gl::Enum ATD::Gl::ALPHA_BITS = GL_ALPHA_BITS;
const ATD::Gl::Enum ATD::Gl::RED_BITS = GL_RED_BITS;
const ATD::Gl::Enum ATD::Gl::GREEN_BITS = GL_GREEN_BITS;
const ATD::Gl::Enum ATD::Gl::BLUE_BITS = GL_BLUE_BITS;
const ATD::Gl::Enum ATD::Gl::INDEX_BITS = GL_INDEX_BITS;
const ATD::Gl::Enum ATD::Gl::SUBPIXEL_BITS = GL_SUBPIXEL_BITS;
const ATD::Gl::Enum ATD::Gl::AUX_BUFFERS = GL_AUX_BUFFERS;
const ATD::Gl::Enum ATD::Gl::READ_BUFFER = GL_READ_BUFFER;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER = GL_DRAW_BUFFER;
const ATD::Gl::Enum ATD::Gl::DOUBLEBUFFER = GL_DOUBLEBUFFER;
const ATD::Gl::Enum ATD::Gl::STEREO = GL_STEREO;
const ATD::Gl::Enum ATD::Gl::BITMAP = GL_BITMAP;
const ATD::Gl::Enum ATD::Gl::COLOR = GL_COLOR;
const ATD::Gl::Enum ATD::Gl::DEPTH = GL_DEPTH;
const ATD::Gl::Enum ATD::Gl::STENCIL = GL_STENCIL;
const ATD::Gl::Enum ATD::Gl::DITHER = GL_DITHER;
const ATD::Gl::Enum ATD::Gl::RGB = GL_RGB;
const ATD::Gl::Enum ATD::Gl::RGBA = GL_RGBA;

/* Implementation limits */
const ATD::Gl::Enum ATD::Gl::MAX_LIST_NESTING = GL_MAX_LIST_NESTING;
const ATD::Gl::Enum ATD::Gl::MAX_EVAL_ORDER = GL_MAX_EVAL_ORDER;
const ATD::Gl::Enum ATD::Gl::MAX_LIGHTS = GL_MAX_LIGHTS;
const ATD::Gl::Enum ATD::Gl::MAX_CLIP_PLANES = GL_MAX_CLIP_PLANES;
const ATD::Gl::Enum ATD::Gl::MAX_TEXTURE_SIZE = GL_MAX_TEXTURE_SIZE;
const ATD::Gl::Enum ATD::Gl::MAX_PIXEL_MAP_TABLE = GL_MAX_PIXEL_MAP_TABLE;
const ATD::Gl::Enum ATD::Gl::MAX_ATTRIB_STACK_DEPTH = 
	GL_MAX_ATTRIB_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::MAX_MODELVIEW_STACK_DEPTH = 
	GL_MAX_MODELVIEW_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::MAX_NAME_STACK_DEPTH = GL_MAX_NAME_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::MAX_PROJECTION_STACK_DEPTH = 
	GL_MAX_PROJECTION_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::MAX_TEXTURE_STACK_DEPTH = 
	GL_MAX_TEXTURE_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::MAX_VIEWPORT_DIMS = GL_MAX_VIEWPORT_DIMS;
const ATD::Gl::Enum ATD::Gl::MAX_CLIENT_ATTRIB_STACK_DEPTH = 
	GL_MAX_CLIENT_ATTRIB_STACK_DEPTH;

/* Gets */
const ATD::Gl::Enum ATD::Gl::ATTRIB_STACK_DEPTH = GL_ATTRIB_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::CLIENT_ATTRIB_STACK_DEPTH = 
	GL_CLIENT_ATTRIB_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::COLOR_CLEAR_VALUE = GL_COLOR_CLEAR_VALUE;
const ATD::Gl::Enum ATD::Gl::COLOR_WRITEMASK = GL_COLOR_WRITEMASK;
const ATD::Gl::Enum ATD::Gl::CURRENT_INDEX = GL_CURRENT_INDEX;
const ATD::Gl::Enum ATD::Gl::CURRENT_COLOR = GL_CURRENT_COLOR;
const ATD::Gl::Enum ATD::Gl::CURRENT_NORMAL = GL_CURRENT_NORMAL;
const ATD::Gl::Enum ATD::Gl::CURRENT_RASTER_COLOR = GL_CURRENT_RASTER_COLOR;
const ATD::Gl::Enum ATD::Gl::CURRENT_RASTER_DISTANCE = 
	GL_CURRENT_RASTER_DISTANCE;
const ATD::Gl::Enum ATD::Gl::CURRENT_RASTER_INDEX = GL_CURRENT_RASTER_INDEX;
const ATD::Gl::Enum ATD::Gl::CURRENT_RASTER_POSITION = 
	GL_CURRENT_RASTER_POSITION;
const ATD::Gl::Enum ATD::Gl::CURRENT_RASTER_TEXTURE_COORDS = 
	GL_CURRENT_RASTER_TEXTURE_COORDS;
const ATD::Gl::Enum ATD::Gl::CURRENT_RASTER_POSITION_VALID = 
	GL_CURRENT_RASTER_POSITION_VALID;
const ATD::Gl::Enum ATD::Gl::CURRENT_TEXTURE_COORDS = 
	GL_CURRENT_TEXTURE_COORDS;
const ATD::Gl::Enum ATD::Gl::INDEX_CLEAR_VALUE = GL_INDEX_CLEAR_VALUE;
const ATD::Gl::Enum ATD::Gl::INDEX_MODE = GL_INDEX_MODE;
const ATD::Gl::Enum ATD::Gl::INDEX_WRITEMASK = GL_INDEX_WRITEMASK;
const ATD::Gl::Enum ATD::Gl::MODELVIEW_MATRIX = GL_MODELVIEW_MATRIX;
const ATD::Gl::Enum ATD::Gl::MODELVIEW_STACK_DEPTH = GL_MODELVIEW_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::NAME_STACK_DEPTH = GL_NAME_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::PROJECTION_MATRIX = GL_PROJECTION_MATRIX;
const ATD::Gl::Enum ATD::Gl::PROJECTION_STACK_DEPTH = 
	GL_PROJECTION_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::RENDER_MODE = GL_RENDER_MODE;
const ATD::Gl::Enum ATD::Gl::RGBA_MODE = GL_RGBA_MODE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_MATRIX = GL_TEXTURE_MATRIX;
const ATD::Gl::Enum ATD::Gl::TEXTURE_STACK_DEPTH = GL_TEXTURE_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::VIEWPORT = GL_VIEWPORT;

/* Evaluators */
const ATD::Gl::Enum ATD::Gl::AUTO_NORMAL = GL_AUTO_NORMAL;
const ATD::Gl::Enum ATD::Gl::MAP1_COLOR_4 = GL_MAP1_COLOR_4;
const ATD::Gl::Enum ATD::Gl::MAP1_INDEX = GL_MAP1_INDEX;
const ATD::Gl::Enum ATD::Gl::MAP1_NORMAL = GL_MAP1_NORMAL;
const ATD::Gl::Enum ATD::Gl::MAP1_TEXTURE_COORD_1 = GL_MAP1_TEXTURE_COORD_1;
const ATD::Gl::Enum ATD::Gl::MAP1_TEXTURE_COORD_2 = GL_MAP1_TEXTURE_COORD_2;
const ATD::Gl::Enum ATD::Gl::MAP1_TEXTURE_COORD_3 = GL_MAP1_TEXTURE_COORD_3;
const ATD::Gl::Enum ATD::Gl::MAP1_TEXTURE_COORD_4 = GL_MAP1_TEXTURE_COORD_4;
const ATD::Gl::Enum ATD::Gl::MAP1_VERTEX_3 = GL_MAP1_VERTEX_3;
const ATD::Gl::Enum ATD::Gl::MAP1_VERTEX_4 = GL_MAP1_VERTEX_4;
const ATD::Gl::Enum ATD::Gl::MAP2_COLOR_4 = GL_MAP2_COLOR_4;
const ATD::Gl::Enum ATD::Gl::MAP2_INDEX = GL_MAP2_INDEX;
const ATD::Gl::Enum ATD::Gl::MAP2_NORMAL = GL_MAP2_NORMAL;
const ATD::Gl::Enum ATD::Gl::MAP2_TEXTURE_COORD_1 = GL_MAP2_TEXTURE_COORD_1;
const ATD::Gl::Enum ATD::Gl::MAP2_TEXTURE_COORD_2 = GL_MAP2_TEXTURE_COORD_2;
const ATD::Gl::Enum ATD::Gl::MAP2_TEXTURE_COORD_3 = GL_MAP2_TEXTURE_COORD_3;
const ATD::Gl::Enum ATD::Gl::MAP2_TEXTURE_COORD_4 = GL_MAP2_TEXTURE_COORD_4;
const ATD::Gl::Enum ATD::Gl::MAP2_VERTEX_3 = GL_MAP2_VERTEX_3;
const ATD::Gl::Enum ATD::Gl::MAP2_VERTEX_4 = GL_MAP2_VERTEX_4;
const ATD::Gl::Enum ATD::Gl::MAP1_GRID_DOMAIN = GL_MAP1_GRID_DOMAIN;
const ATD::Gl::Enum ATD::Gl::MAP1_GRID_SEGMENTS = GL_MAP1_GRID_SEGMENTS;
const ATD::Gl::Enum ATD::Gl::MAP2_GRID_DOMAIN = GL_MAP2_GRID_DOMAIN;
const ATD::Gl::Enum ATD::Gl::MAP2_GRID_SEGMENTS = GL_MAP2_GRID_SEGMENTS;
const ATD::Gl::Enum ATD::Gl::COEFF = GL_COEFF;
const ATD::Gl::Enum ATD::Gl::ORDER = GL_ORDER;
const ATD::Gl::Enum ATD::Gl::M_DOMAIN = GL_DOMAIN;

/* Hints */
const ATD::Gl::Enum ATD::Gl::PERSPECTIVE_CORRECTION_HINT = 
	GL_PERSPECTIVE_CORRECTION_HINT;
const ATD::Gl::Enum ATD::Gl::POINT_SMOOTH_HINT = GL_POINT_SMOOTH_HINT;
const ATD::Gl::Enum ATD::Gl::LINE_SMOOTH_HINT = GL_LINE_SMOOTH_HINT;
const ATD::Gl::Enum ATD::Gl::POLYGON_SMOOTH_HINT = GL_POLYGON_SMOOTH_HINT;
const ATD::Gl::Enum ATD::Gl::FOG_HINT = GL_FOG_HINT;
const ATD::Gl::Enum ATD::Gl::DONT_CARE = GL_DONT_CARE;
const ATD::Gl::Enum ATD::Gl::FASTEST = GL_FASTEST;
const ATD::Gl::Enum ATD::Gl::NICEST = GL_NICEST;

/* Scissor box */
const ATD::Gl::Enum ATD::Gl::SCISSOR_BOX = GL_SCISSOR_BOX;
const ATD::Gl::Enum ATD::Gl::SCISSOR_TEST = GL_SCISSOR_TEST;

/* Pixel Mode / Transfer */
const ATD::Gl::Enum ATD::Gl::MAP_COLOR = GL_MAP_COLOR;
const ATD::Gl::Enum ATD::Gl::MAP_STENCIL = GL_MAP_STENCIL;
const ATD::Gl::Enum ATD::Gl::INDEX_SHIFT = GL_INDEX_SHIFT;
const ATD::Gl::Enum ATD::Gl::INDEX_OFFSET = GL_INDEX_OFFSET;
const ATD::Gl::Enum ATD::Gl::RED_SCALE = GL_RED_SCALE;
const ATD::Gl::Enum ATD::Gl::RED_BIAS = GL_RED_BIAS;
const ATD::Gl::Enum ATD::Gl::GREEN_SCALE = GL_GREEN_SCALE;
const ATD::Gl::Enum ATD::Gl::GREEN_BIAS = GL_GREEN_BIAS;
const ATD::Gl::Enum ATD::Gl::BLUE_SCALE = GL_BLUE_SCALE;
const ATD::Gl::Enum ATD::Gl::BLUE_BIAS = GL_BLUE_BIAS;
const ATD::Gl::Enum ATD::Gl::ALPHA_SCALE = GL_ALPHA_SCALE;
const ATD::Gl::Enum ATD::Gl::ALPHA_BIAS = GL_ALPHA_BIAS;
const ATD::Gl::Enum ATD::Gl::DEPTH_SCALE = GL_DEPTH_SCALE;
const ATD::Gl::Enum ATD::Gl::DEPTH_BIAS = GL_DEPTH_BIAS;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_S_TO_S_SIZE = GL_PIXEL_MAP_S_TO_S_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_I_SIZE = GL_PIXEL_MAP_I_TO_I_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_R_SIZE = GL_PIXEL_MAP_I_TO_R_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_G_SIZE = GL_PIXEL_MAP_I_TO_G_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_B_SIZE = GL_PIXEL_MAP_I_TO_B_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_A_SIZE = GL_PIXEL_MAP_I_TO_A_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_R_TO_R_SIZE = GL_PIXEL_MAP_R_TO_R_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_G_TO_G_SIZE = GL_PIXEL_MAP_G_TO_G_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_B_TO_B_SIZE = GL_PIXEL_MAP_B_TO_B_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_A_TO_A_SIZE = GL_PIXEL_MAP_A_TO_A_SIZE;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_S_TO_S = GL_PIXEL_MAP_S_TO_S;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_I = GL_PIXEL_MAP_I_TO_I;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_R = GL_PIXEL_MAP_I_TO_R;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_G = GL_PIXEL_MAP_I_TO_G;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_B = GL_PIXEL_MAP_I_TO_B;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_I_TO_A = GL_PIXEL_MAP_I_TO_A;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_R_TO_R = GL_PIXEL_MAP_R_TO_R;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_G_TO_G = GL_PIXEL_MAP_G_TO_G;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_B_TO_B = GL_PIXEL_MAP_B_TO_B;
const ATD::Gl::Enum ATD::Gl::PIXEL_MAP_A_TO_A = GL_PIXEL_MAP_A_TO_A;
const ATD::Gl::Enum ATD::Gl::PACK_ALIGNMENT = GL_PACK_ALIGNMENT;
const ATD::Gl::Enum ATD::Gl::PACK_LSB_FIRST = GL_PACK_LSB_FIRST;
const ATD::Gl::Enum ATD::Gl::PACK_ROW_LENGTH = GL_PACK_ROW_LENGTH;
const ATD::Gl::Enum ATD::Gl::PACK_SKIP_PIXELS = GL_PACK_SKIP_PIXELS;
const ATD::Gl::Enum ATD::Gl::PACK_SKIP_ROWS = GL_PACK_SKIP_ROWS;
const ATD::Gl::Enum ATD::Gl::PACK_SWAP_BYTES = GL_PACK_SWAP_BYTES;
const ATD::Gl::Enum ATD::Gl::UNPACK_ALIGNMENT = GL_UNPACK_ALIGNMENT;
const ATD::Gl::Enum ATD::Gl::UNPACK_LSB_FIRST = GL_UNPACK_LSB_FIRST;
const ATD::Gl::Enum ATD::Gl::UNPACK_ROW_LENGTH = GL_UNPACK_ROW_LENGTH;
const ATD::Gl::Enum ATD::Gl::UNPACK_SKIP_PIXELS = GL_UNPACK_SKIP_PIXELS;
const ATD::Gl::Enum ATD::Gl::UNPACK_SKIP_ROWS = GL_UNPACK_SKIP_ROWS;
const ATD::Gl::Enum ATD::Gl::UNPACK_SWAP_BYTES = GL_UNPACK_SWAP_BYTES;
const ATD::Gl::Enum ATD::Gl::ZOOM_X = GL_ZOOM_X;
const ATD::Gl::Enum ATD::Gl::ZOOM_Y = GL_ZOOM_Y;

/* Texture mapping */
const ATD::Gl::Enum ATD::Gl::TEXTURE_ENV = GL_TEXTURE_ENV;
const ATD::Gl::Enum ATD::Gl::TEXTURE_ENV_MODE = GL_TEXTURE_ENV_MODE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_1D = GL_TEXTURE_1D;
const ATD::Gl::Enum ATD::Gl::TEXTURE_2D = GL_TEXTURE_2D;
const ATD::Gl::Enum ATD::Gl::TEXTURE_WRAP_S = GL_TEXTURE_WRAP_S;
const ATD::Gl::Enum ATD::Gl::TEXTURE_WRAP_T = GL_TEXTURE_WRAP_T;
const ATD::Gl::Enum ATD::Gl::TEXTURE_MAG_FILTER = GL_TEXTURE_MAG_FILTER;
const ATD::Gl::Enum ATD::Gl::TEXTURE_MIN_FILTER = GL_TEXTURE_MIN_FILTER;
const ATD::Gl::Enum ATD::Gl::TEXTURE_ENV_COLOR = GL_TEXTURE_ENV_COLOR;
const ATD::Gl::Enum ATD::Gl::TEXTURE_GEN_S = GL_TEXTURE_GEN_S;
const ATD::Gl::Enum ATD::Gl::TEXTURE_GEN_T = GL_TEXTURE_GEN_T;
const ATD::Gl::Enum ATD::Gl::TEXTURE_GEN_R = GL_TEXTURE_GEN_R;
const ATD::Gl::Enum ATD::Gl::TEXTURE_GEN_Q = GL_TEXTURE_GEN_Q;
const ATD::Gl::Enum ATD::Gl::TEXTURE_GEN_MODE = GL_TEXTURE_GEN_MODE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BORDER_COLOR = GL_TEXTURE_BORDER_COLOR;
const ATD::Gl::Enum ATD::Gl::TEXTURE_WIDTH = GL_TEXTURE_WIDTH;
const ATD::Gl::Enum ATD::Gl::TEXTURE_HEIGHT = GL_TEXTURE_HEIGHT;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BORDER = GL_TEXTURE_BORDER;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COMPONENTS = GL_TEXTURE_COMPONENTS;
const ATD::Gl::Enum ATD::Gl::TEXTURE_RED_SIZE = GL_TEXTURE_RED_SIZE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_GREEN_SIZE = GL_TEXTURE_GREEN_SIZE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BLUE_SIZE = GL_TEXTURE_BLUE_SIZE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_ALPHA_SIZE = GL_TEXTURE_ALPHA_SIZE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_LUMINANCE_SIZE = 
	GL_TEXTURE_LUMINANCE_SIZE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_INTENSITY_SIZE = 
	GL_TEXTURE_INTENSITY_SIZE;
const ATD::Gl::Enum ATD::Gl::NEAREST_MIPMAP_NEAREST = 
	GL_NEAREST_MIPMAP_NEAREST;
const ATD::Gl::Enum ATD::Gl::NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR;
const ATD::Gl::Enum ATD::Gl::LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST;
const ATD::Gl::Enum ATD::Gl::LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR;
const ATD::Gl::Enum ATD::Gl::OBJECT_LINEAR = GL_OBJECT_LINEAR;
const ATD::Gl::Enum ATD::Gl::OBJECT_PLANE = GL_OBJECT_PLANE;
const ATD::Gl::Enum ATD::Gl::EYE_LINEAR = GL_EYE_LINEAR;
const ATD::Gl::Enum ATD::Gl::EYE_PLANE = GL_EYE_PLANE;
const ATD::Gl::Enum ATD::Gl::SPHERE_MAP = GL_SPHERE_MAP;
const ATD::Gl::Enum ATD::Gl::DECAL = GL_DECAL;
const ATD::Gl::Enum ATD::Gl::MODULATE = GL_MODULATE;
const ATD::Gl::Enum ATD::Gl::NEAREST = GL_NEAREST;
const ATD::Gl::Enum ATD::Gl::REPEAT = GL_REPEAT;
const ATD::Gl::Enum ATD::Gl::CLAMP = GL_CLAMP;
const ATD::Gl::Enum ATD::Gl::S = GL_S;
const ATD::Gl::Enum ATD::Gl::T = GL_T;
const ATD::Gl::Enum ATD::Gl::R = GL_R;
const ATD::Gl::Enum ATD::Gl::Q = GL_Q;

/* Utility */
const ATD::Gl::Enum ATD::Gl::VENDOR = GL_VENDOR;
const ATD::Gl::Enum ATD::Gl::RENDERER = GL_RENDERER;
const ATD::Gl::Enum ATD::Gl::VERSION = GL_VERSION;
const ATD::Gl::Enum ATD::Gl::EXTENSIONS = GL_EXTENSIONS;

/* Errors */
const ATD::Gl::Enum ATD::Gl::NO_ERROR = GL_NO_ERROR;
const ATD::Gl::Enum ATD::Gl::INVALID_ENUM = GL_INVALID_ENUM;
const ATD::Gl::Enum ATD::Gl::INVALID_VALUE = GL_INVALID_VALUE;
const ATD::Gl::Enum ATD::Gl::INVALID_OPERATION = GL_INVALID_OPERATION;
const ATD::Gl::Enum ATD::Gl::STACK_OVERFLOW = GL_STACK_OVERFLOW;
const ATD::Gl::Enum ATD::Gl::STACK_UNDERFLOW = GL_STACK_UNDERFLOW;
const ATD::Gl::Enum ATD::Gl::OUT_OF_MEMORY = GL_OUT_OF_MEMORY;

/* glPush/PopAttrib bits */
const ATD::Gl::Bitfield ATD::Gl::CURRENT_BIT = GL_CURRENT_BIT;
const ATD::Gl::Bitfield ATD::Gl::POINT_BIT = GL_POINT_BIT;
const ATD::Gl::Bitfield ATD::Gl::LINE_BIT = GL_LINE_BIT;
const ATD::Gl::Bitfield ATD::Gl::POLYGON_BIT = GL_POLYGON_BIT;
const ATD::Gl::Bitfield ATD::Gl::POLYGON_STIPPLE_BIT = GL_POLYGON_STIPPLE_BIT;
const ATD::Gl::Bitfield ATD::Gl::PIXEL_MODE_BIT = GL_PIXEL_MODE_BIT;
const ATD::Gl::Bitfield ATD::Gl::LIGHTING_BIT = GL_LIGHTING_BIT;
const ATD::Gl::Bitfield ATD::Gl::FOG_BIT = GL_FOG_BIT;
const ATD::Gl::Bitfield ATD::Gl::DEPTH_BUFFER_BIT = GL_DEPTH_BUFFER_BIT;
const ATD::Gl::Bitfield ATD::Gl::ACCUM_BUFFER_BIT = GL_ACCUM_BUFFER_BIT;
const ATD::Gl::Bitfield ATD::Gl::STENCIL_BUFFER_BIT = GL_STENCIL_BUFFER_BIT;
const ATD::Gl::Bitfield ATD::Gl::VIEWPORT_BIT = GL_VIEWPORT_BIT;
const ATD::Gl::Bitfield ATD::Gl::TRANSFORM_BIT = GL_TRANSFORM_BIT;
const ATD::Gl::Bitfield ATD::Gl::ENABLE_BIT = GL_ENABLE_BIT;
const ATD::Gl::Bitfield ATD::Gl::COLOR_BUFFER_BIT = GL_COLOR_BUFFER_BIT;
const ATD::Gl::Bitfield ATD::Gl::HINT_BIT = GL_HINT_BIT;
const ATD::Gl::Bitfield ATD::Gl::EVAL_BIT = GL_EVAL_BIT;
const ATD::Gl::Bitfield ATD::Gl::LIST_BIT = GL_LIST_BIT;
const ATD::Gl::Bitfield ATD::Gl::TEXTURE_BIT = GL_TEXTURE_BIT;
const ATD::Gl::Bitfield ATD::Gl::SCISSOR_BIT = GL_SCISSOR_BIT;
const ATD::Gl::Bitfield ATD::Gl::ALL_ATTRIB_BITS = GL_ALL_ATTRIB_BITS;

/* OpenGL 1.1 */
const ATD::Gl::Enum ATD::Gl::PROXY_TEXTURE_1D = GL_PROXY_TEXTURE_1D;
const ATD::Gl::Enum ATD::Gl::PROXY_TEXTURE_2D = GL_PROXY_TEXTURE_2D;
const ATD::Gl::Enum ATD::Gl::TEXTURE_PRIORITY = GL_TEXTURE_PRIORITY;
const ATD::Gl::Enum ATD::Gl::TEXTURE_RESIDENT = GL_TEXTURE_RESIDENT;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BINDING_1D = GL_TEXTURE_BINDING_1D;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BINDING_2D = GL_TEXTURE_BINDING_2D;
const ATD::Gl::Enum ATD::Gl::TEXTURE_INTERNAL_FORMAT = 
	GL_TEXTURE_INTERNAL_FORMAT;
const ATD::Gl::Enum ATD::Gl::ALPHA4 = GL_ALPHA4;
const ATD::Gl::Enum ATD::Gl::ALPHA8 = GL_ALPHA8;
const ATD::Gl::Enum ATD::Gl::ALPHA12 = GL_ALPHA12;
const ATD::Gl::Enum ATD::Gl::ALPHA16 = GL_ALPHA16;
const ATD::Gl::Enum ATD::Gl::LUMINANCE4 = GL_LUMINANCE4;
const ATD::Gl::Enum ATD::Gl::LUMINANCE8 = GL_LUMINANCE8;
const ATD::Gl::Enum ATD::Gl::LUMINANCE12 = GL_LUMINANCE12;
const ATD::Gl::Enum ATD::Gl::LUMINANCE16 = GL_LUMINANCE16;
const ATD::Gl::Enum ATD::Gl::LUMINANCE4_ALPHA4 = GL_LUMINANCE4_ALPHA4;
const ATD::Gl::Enum ATD::Gl::LUMINANCE6_ALPHA2 = GL_LUMINANCE6_ALPHA2;
const ATD::Gl::Enum ATD::Gl::LUMINANCE8_ALPHA8 = GL_LUMINANCE8_ALPHA8;
const ATD::Gl::Enum ATD::Gl::LUMINANCE12_ALPHA4 = GL_LUMINANCE12_ALPHA4;
const ATD::Gl::Enum ATD::Gl::LUMINANCE12_ALPHA12 = GL_LUMINANCE12_ALPHA12;
const ATD::Gl::Enum ATD::Gl::LUMINANCE16_ALPHA16 = GL_LUMINANCE16_ALPHA16;
const ATD::Gl::Enum ATD::Gl::INTENSITY = GL_INTENSITY;
const ATD::Gl::Enum ATD::Gl::INTENSITY4 = GL_INTENSITY4;
const ATD::Gl::Enum ATD::Gl::INTENSITY8 = GL_INTENSITY8;
const ATD::Gl::Enum ATD::Gl::INTENSITY12 = GL_INTENSITY12;
const ATD::Gl::Enum ATD::Gl::INTENSITY16 = GL_INTENSITY16;
const ATD::Gl::Enum ATD::Gl::R3_G3_B2 = GL_R3_G3_B2;
const ATD::Gl::Enum ATD::Gl::RGB4 = GL_RGB4;
const ATD::Gl::Enum ATD::Gl::RGB5 = GL_RGB5;
const ATD::Gl::Enum ATD::Gl::RGB8 = GL_RGB8;
const ATD::Gl::Enum ATD::Gl::RGB10 = GL_RGB10;
const ATD::Gl::Enum ATD::Gl::RGB12 = GL_RGB12;
const ATD::Gl::Enum ATD::Gl::RGB16 = GL_RGB16;
const ATD::Gl::Enum ATD::Gl::RGBA2 = GL_RGBA2;
const ATD::Gl::Enum ATD::Gl::RGBA4 = GL_RGBA4;
const ATD::Gl::Enum ATD::Gl::RGB5_A1 = GL_RGB5_A1;
const ATD::Gl::Enum ATD::Gl::RGBA8 = GL_RGBA8;
const ATD::Gl::Enum ATD::Gl::RGB10_A2 = GL_RGB10_A2;
const ATD::Gl::Enum ATD::Gl::RGBA12 = GL_RGBA12;
const ATD::Gl::Enum ATD::Gl::RGBA16 = GL_RGBA16;
const ATD::Gl::Bitfield ATD::Gl::CLIENT_PIXEL_STORE_BIT = 
	GL_CLIENT_PIXEL_STORE_BIT;
const ATD::Gl::Bitfield ATD::Gl::CLIENT_VERTEX_ARRAY_BIT = 
	GL_CLIENT_VERTEX_ARRAY_BIT;
const ATD::Gl::Bitfield ATD::Gl::ALL_CLIENT_ATTRIB_BITS = 
	GL_ALL_CLIENT_ATTRIB_BITS;
const ATD::Gl::Bitfield ATD::Gl::CLIENT_ALL_ATTRIB_BITS = 
	GL_CLIENT_ALL_ATTRIB_BITS;

/* OpenGL 1.2 */
const ATD::Gl::Enum ATD::Gl::RESCALE_NORMAL = GL_RESCALE_NORMAL;
const ATD::Gl::Enum ATD::Gl::CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE;
const ATD::Gl::Enum ATD::Gl::MAX_ELEMENTS_VERTICES = GL_MAX_ELEMENTS_VERTICES;
const ATD::Gl::Enum ATD::Gl::MAX_ELEMENTS_INDICES = GL_MAX_ELEMENTS_INDICES;
const ATD::Gl::Enum ATD::Gl::BGR = GL_BGR;
const ATD::Gl::Enum ATD::Gl::BGRA = GL_BGRA;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_BYTE_3_3_2 = GL_UNSIGNED_BYTE_3_3_2;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_BYTE_2_3_3_REV = 
	GL_UNSIGNED_BYTE_2_3_3_REV;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_SHORT_5_6_5 = GL_UNSIGNED_SHORT_5_6_5;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_SHORT_5_6_5_REV = 
	GL_UNSIGNED_SHORT_5_6_5_REV;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_SHORT_4_4_4_4 = 
	GL_UNSIGNED_SHORT_4_4_4_4;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_SHORT_4_4_4_4_REV = 
	GL_UNSIGNED_SHORT_4_4_4_4_REV;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_SHORT_5_5_5_1 = 
	GL_UNSIGNED_SHORT_5_5_5_1;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_SHORT_1_5_5_5_REV = 
	GL_UNSIGNED_SHORT_1_5_5_5_REV;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_8_8_8_8 = GL_UNSIGNED_INT_8_8_8_8;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_8_8_8_8_REV = 
	GL_UNSIGNED_INT_8_8_8_8_REV;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_10_10_10_2 = 
	GL_UNSIGNED_INT_10_10_10_2;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_2_10_10_10_REV = 
	GL_UNSIGNED_INT_2_10_10_10_REV;
const ATD::Gl::Enum ATD::Gl::LIGHT_MODEL_COLOR_CONTROL = 
	GL_LIGHT_MODEL_COLOR_CONTROL;
const ATD::Gl::Enum ATD::Gl::SINGLE_COLOR = GL_SINGLE_COLOR;
const ATD::Gl::Enum ATD::Gl::SEPARATE_SPECULAR_COLOR = 
	GL_SEPARATE_SPECULAR_COLOR;
const ATD::Gl::Enum ATD::Gl::TEXTURE_MIN_LOD = GL_TEXTURE_MIN_LOD;
const ATD::Gl::Enum ATD::Gl::TEXTURE_MAX_LOD = GL_TEXTURE_MAX_LOD;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BASE_LEVEL = GL_TEXTURE_BASE_LEVEL;
const ATD::Gl::Enum ATD::Gl::TEXTURE_MAX_LEVEL = GL_TEXTURE_MAX_LEVEL;
const ATD::Gl::Enum ATD::Gl::SMOOTH_POINT_SIZE_RANGE = 
	GL_SMOOTH_POINT_SIZE_RANGE;
const ATD::Gl::Enum ATD::Gl::SMOOTH_POINT_SIZE_GRANULARITY = 
	GL_SMOOTH_POINT_SIZE_GRANULARITY;
const ATD::Gl::Enum ATD::Gl::SMOOTH_LINE_WIDTH_RANGE = 
	GL_SMOOTH_LINE_WIDTH_RANGE;
const ATD::Gl::Enum ATD::Gl::SMOOTH_LINE_WIDTH_GRANULARITY = 
	GL_SMOOTH_LINE_WIDTH_GRANULARITY;
const ATD::Gl::Enum ATD::Gl::ALIASED_POINT_SIZE_RANGE = 
	GL_ALIASED_POINT_SIZE_RANGE;
const ATD::Gl::Enum ATD::Gl::ALIASED_LINE_WIDTH_RANGE = 
	GL_ALIASED_LINE_WIDTH_RANGE;
const ATD::Gl::Enum ATD::Gl::PACK_SKIP_IMAGES = GL_PACK_SKIP_IMAGES;
const ATD::Gl::Enum ATD::Gl::PACK_IMAGE_HEIGHT = GL_PACK_IMAGE_HEIGHT;
const ATD::Gl::Enum ATD::Gl::UNPACK_SKIP_IMAGES = GL_UNPACK_SKIP_IMAGES;
const ATD::Gl::Enum ATD::Gl::UNPACK_IMAGE_HEIGHT = GL_UNPACK_IMAGE_HEIGHT;
const ATD::Gl::Enum ATD::Gl::TEXTURE_3D = GL_TEXTURE_3D;
const ATD::Gl::Enum ATD::Gl::PROXY_TEXTURE_3D = GL_PROXY_TEXTURE_3D;
const ATD::Gl::Enum ATD::Gl::TEXTURE_DEPTH = GL_TEXTURE_DEPTH;
const ATD::Gl::Enum ATD::Gl::TEXTURE_WRAP_R = GL_TEXTURE_WRAP_R;
const ATD::Gl::Enum ATD::Gl::MAX_3D_TEXTURE_SIZE = GL_MAX_3D_TEXTURE_SIZE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BINDING_3D = GL_TEXTURE_BINDING_3D;

/* GL_ARB_imaging */
const ATD::Gl::Enum ATD::Gl::CONSTANT_COLOR = GL_CONSTANT_COLOR;
const ATD::Gl::Enum ATD::Gl::ONE_MINUS_CONSTANT_COLOR = 
	GL_ONE_MINUS_CONSTANT_COLOR;
const ATD::Gl::Enum ATD::Gl::CONSTANT_ALPHA = GL_CONSTANT_ALPHA;
const ATD::Gl::Enum ATD::Gl::ONE_MINUS_CONSTANT_ALPHA = 
	GL_ONE_MINUS_CONSTANT_ALPHA;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE = GL_COLOR_TABLE;
const ATD::Gl::Enum ATD::Gl::POST_CONVOLUTION_COLOR_TABLE = 
	GL_POST_CONVOLUTION_COLOR_TABLE;
const ATD::Gl::Enum ATD::Gl::POST_COLOR_MATRIX_COLOR_TABLE = 
	GL_POST_COLOR_MATRIX_COLOR_TABLE;
const ATD::Gl::Enum ATD::Gl::PROXY_COLOR_TABLE = GL_PROXY_COLOR_TABLE;
const ATD::Gl::Enum ATD::Gl::PROXY_POST_CONVOLUTION_COLOR_TABLE = 
	GL_PROXY_POST_CONVOLUTION_COLOR_TABLE;
const ATD::Gl::Enum ATD::Gl::PROXY_POST_COLOR_MATRIX_COLOR_TABLE = 
	GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_SCALE = GL_COLOR_TABLE_SCALE;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_BIAS = GL_COLOR_TABLE_BIAS;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_FORMAT = GL_COLOR_TABLE_FORMAT;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_WIDTH = GL_COLOR_TABLE_WIDTH;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_RED_SIZE = GL_COLOR_TABLE_RED_SIZE;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_GREEN_SIZE = 
	GL_COLOR_TABLE_GREEN_SIZE;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_BLUE_SIZE = GL_COLOR_TABLE_BLUE_SIZE;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_ALPHA_SIZE = 
	GL_COLOR_TABLE_ALPHA_SIZE;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_LUMINANCE_SIZE = 
	GL_COLOR_TABLE_LUMINANCE_SIZE;
const ATD::Gl::Enum ATD::Gl::COLOR_TABLE_INTENSITY_SIZE = 
	GL_COLOR_TABLE_INTENSITY_SIZE;
const ATD::Gl::Enum ATD::Gl::CONVOLUTION_1D = GL_CONVOLUTION_1D;
const ATD::Gl::Enum ATD::Gl::CONVOLUTION_2D = GL_CONVOLUTION_2D;
const ATD::Gl::Enum ATD::Gl::SEPARABLE_2D = GL_SEPARABLE_2D;
const ATD::Gl::Enum ATD::Gl::CONVOLUTION_BORDER_MODE = 
	GL_CONVOLUTION_BORDER_MODE;
const ATD::Gl::Enum ATD::Gl::CONVOLUTION_FILTER_SCALE = 
	GL_CONVOLUTION_FILTER_SCALE;
const ATD::Gl::Enum ATD::Gl::CONVOLUTION_FILTER_BIAS = 
	GL_CONVOLUTION_FILTER_BIAS;
const ATD::Gl::Enum ATD::Gl::REDUCE = GL_REDUCE;
const ATD::Gl::Enum ATD::Gl::CONVOLUTION_FORMAT = GL_CONVOLUTION_FORMAT;
const ATD::Gl::Enum ATD::Gl::CONVOLUTION_WIDTH = GL_CONVOLUTION_WIDTH;
const ATD::Gl::Enum ATD::Gl::CONVOLUTION_HEIGHT = GL_CONVOLUTION_HEIGHT;
const ATD::Gl::Enum ATD::Gl::MAX_CONVOLUTION_WIDTH = GL_MAX_CONVOLUTION_WIDTH;
const ATD::Gl::Enum ATD::Gl::MAX_CONVOLUTION_HEIGHT = 
	GL_MAX_CONVOLUTION_HEIGHT;
const ATD::Gl::Enum ATD::Gl::POST_CONVOLUTION_RED_SCALE = 
	GL_POST_CONVOLUTION_RED_SCALE;
const ATD::Gl::Enum ATD::Gl::POST_CONVOLUTION_GREEN_SCALE = 
	GL_POST_CONVOLUTION_GREEN_SCALE;
const ATD::Gl::Enum ATD::Gl::POST_CONVOLUTION_BLUE_SCALE = 
	GL_POST_CONVOLUTION_BLUE_SCALE;
const ATD::Gl::Enum ATD::Gl::POST_CONVOLUTION_ALPHA_SCALE = 
	GL_POST_CONVOLUTION_ALPHA_SCALE;
const ATD::Gl::Enum ATD::Gl::POST_CONVOLUTION_RED_BIAS = 
	GL_POST_CONVOLUTION_RED_BIAS;
const ATD::Gl::Enum ATD::Gl::POST_CONVOLUTION_GREEN_BIAS = 
	GL_POST_CONVOLUTION_GREEN_BIAS;
const ATD::Gl::Enum ATD::Gl::POST_CONVOLUTION_BLUE_BIAS = 
	GL_POST_CONVOLUTION_BLUE_BIAS;
const ATD::Gl::Enum ATD::Gl::POST_CONVOLUTION_ALPHA_BIAS = 
	GL_POST_CONVOLUTION_ALPHA_BIAS;
const ATD::Gl::Enum ATD::Gl::CONSTANT_BORDER = GL_CONSTANT_BORDER;
const ATD::Gl::Enum ATD::Gl::REPLICATE_BORDER = GL_REPLICATE_BORDER;
const ATD::Gl::Enum ATD::Gl::CONVOLUTION_BORDER_COLOR = 
	GL_CONVOLUTION_BORDER_COLOR;
const ATD::Gl::Enum ATD::Gl::COLOR_MATRIX = GL_COLOR_MATRIX;
const ATD::Gl::Enum ATD::Gl::COLOR_MATRIX_STACK_DEPTH = 
	GL_COLOR_MATRIX_STACK_DEPTH;
const ATD::Gl::Enum ATD::Gl::MAX_COLOR_MATRIX_STACK_DEPTH = 
	GL_MAX_COLOR_MATRIX_STACK_DEPTH_SGI;
const ATD::Gl::Enum ATD::Gl::POST_COLOR_MATRIX_RED_SCALE = 
	GL_POST_COLOR_MATRIX_RED_SCALE;
const ATD::Gl::Enum ATD::Gl::POST_COLOR_MATRIX_GREEN_SCALE = 
	GL_POST_COLOR_MATRIX_GREEN_SCALE;
const ATD::Gl::Enum ATD::Gl::POST_COLOR_MATRIX_BLUE_SCALE = 
	GL_POST_COLOR_MATRIX_BLUE_SCALE;
const ATD::Gl::Enum ATD::Gl::POST_COLOR_MATRIX_ALPHA_SCALE = 
	GL_POST_COLOR_MATRIX_ALPHA_SCALE;
const ATD::Gl::Enum ATD::Gl::POST_COLOR_MATRIX_RED_BIAS = 
	GL_POST_COLOR_MATRIX_RED_BIAS;
const ATD::Gl::Enum ATD::Gl::POST_COLOR_MATRIX_GREEN_BIAS = 
	GL_POST_COLOR_MATRIX_GREEN_BIAS;
const ATD::Gl::Enum ATD::Gl::POST_COLOR_MATRIX_BLUE_BIAS = 
	GL_POST_COLOR_MATRIX_BLUE_BIAS;
const ATD::Gl::Enum ATD::Gl::POST_COLOR_MATRIX_ALPHA_BIAS = 
	GL_POST_COLOR_MATRIX_ALPHA_BIAS;
const ATD::Gl::Enum ATD::Gl::HISTOGRAM = GL_HISTOGRAM;
const ATD::Gl::Enum ATD::Gl::PROXY_HISTOGRAM = GL_PROXY_HISTOGRAM;
const ATD::Gl::Enum ATD::Gl::HISTOGRAM_WIDTH = GL_HISTOGRAM_WIDTH;
const ATD::Gl::Enum ATD::Gl::HISTOGRAM_FORMAT = GL_HISTOGRAM_FORMAT;
const ATD::Gl::Enum ATD::Gl::HISTOGRAM_RED_SIZE = GL_HISTOGRAM_RED_SIZE;
const ATD::Gl::Enum ATD::Gl::HISTOGRAM_GREEN_SIZE = GL_HISTOGRAM_GREEN_SIZE;
const ATD::Gl::Enum ATD::Gl::HISTOGRAM_BLUE_SIZE = GL_HISTOGRAM_BLUE_SIZE;
const ATD::Gl::Enum ATD::Gl::HISTOGRAM_ALPHA_SIZE = GL_HISTOGRAM_ALPHA_SIZE;
const ATD::Gl::Enum ATD::Gl::HISTOGRAM_LUMINANCE_SIZE = 
	GL_HISTOGRAM_LUMINANCE_SIZE;
const ATD::Gl::Enum ATD::Gl::HISTOGRAM_SINK = GL_HISTOGRAM_SINK;
const ATD::Gl::Enum ATD::Gl::MINMAX = GL_MINMAX;
const ATD::Gl::Enum ATD::Gl::MINMAX_FORMAT = GL_MINMAX_FORMAT;
const ATD::Gl::Enum ATD::Gl::MINMAX_SINK = GL_MINMAX_SINK;
const ATD::Gl::Enum ATD::Gl::TABLE_TOO_LARGE = GL_TABLE_TOO_LARGE;
const ATD::Gl::Enum ATD::Gl::BLEND_EQUATION = GL_BLEND_EQUATION;
const ATD::Gl::Enum ATD::Gl::MIN = GL_MIN;
const ATD::Gl::Enum ATD::Gl::MAX = GL_MAX;
const ATD::Gl::Enum ATD::Gl::FUNC_ADD = GL_FUNC_ADD;
const ATD::Gl::Enum ATD::Gl::FUNC_SUBTRACT = GL_FUNC_SUBTRACT;
const ATD::Gl::Enum ATD::Gl::FUNC_REVERSE_SUBTRACT = GL_FUNC_REVERSE_SUBTRACT;
const ATD::Gl::Enum ATD::Gl::BLEND_COLOR = GL_BLEND_COLOR;

/* OpenGL 1.3 */
/* multitexture */
const ATD::Gl::Enum ATD::Gl::TEXTURE0 = GL_TEXTURE0;
const ATD::Gl::Enum ATD::Gl::TEXTURE1 = GL_TEXTURE1;
const ATD::Gl::Enum ATD::Gl::TEXTURE2 = GL_TEXTURE2;
const ATD::Gl::Enum ATD::Gl::TEXTURE3 = GL_TEXTURE3;
const ATD::Gl::Enum ATD::Gl::TEXTURE4 = GL_TEXTURE4;
const ATD::Gl::Enum ATD::Gl::TEXTURE5 = GL_TEXTURE5;
const ATD::Gl::Enum ATD::Gl::TEXTURE6 = GL_TEXTURE6;
const ATD::Gl::Enum ATD::Gl::TEXTURE7 = GL_TEXTURE7;
const ATD::Gl::Enum ATD::Gl::TEXTURE8 = GL_TEXTURE8;
const ATD::Gl::Enum ATD::Gl::TEXTURE9 = GL_TEXTURE9;
const ATD::Gl::Enum ATD::Gl::TEXTURE10 = GL_TEXTURE10;
const ATD::Gl::Enum ATD::Gl::TEXTURE11 = GL_TEXTURE11;
const ATD::Gl::Enum ATD::Gl::TEXTURE12 = GL_TEXTURE12;
const ATD::Gl::Enum ATD::Gl::TEXTURE13 = GL_TEXTURE13;
const ATD::Gl::Enum ATD::Gl::TEXTURE14 = GL_TEXTURE14;
const ATD::Gl::Enum ATD::Gl::TEXTURE15 = GL_TEXTURE15;
const ATD::Gl::Enum ATD::Gl::TEXTURE16 = GL_TEXTURE16;
const ATD::Gl::Enum ATD::Gl::TEXTURE17 = GL_TEXTURE17;
const ATD::Gl::Enum ATD::Gl::TEXTURE18 = GL_TEXTURE18;
const ATD::Gl::Enum ATD::Gl::TEXTURE19 = GL_TEXTURE19;
const ATD::Gl::Enum ATD::Gl::TEXTURE20 = GL_TEXTURE20;
const ATD::Gl::Enum ATD::Gl::TEXTURE21 = GL_TEXTURE21;
const ATD::Gl::Enum ATD::Gl::TEXTURE22 = GL_TEXTURE22;
const ATD::Gl::Enum ATD::Gl::TEXTURE23 = GL_TEXTURE23;
const ATD::Gl::Enum ATD::Gl::TEXTURE24 = GL_TEXTURE24;
const ATD::Gl::Enum ATD::Gl::TEXTURE25 = GL_TEXTURE25;
const ATD::Gl::Enum ATD::Gl::TEXTURE26 = GL_TEXTURE26;
const ATD::Gl::Enum ATD::Gl::TEXTURE27 = GL_TEXTURE27;
const ATD::Gl::Enum ATD::Gl::TEXTURE28 = GL_TEXTURE28;
const ATD::Gl::Enum ATD::Gl::TEXTURE29 = GL_TEXTURE29;
const ATD::Gl::Enum ATD::Gl::TEXTURE30 = GL_TEXTURE30;
const ATD::Gl::Enum ATD::Gl::TEXTURE31 = GL_TEXTURE31;
const ATD::Gl::Enum ATD::Gl::ACTIVE_TEXTURE = GL_ACTIVE_TEXTURE;
const ATD::Gl::Enum ATD::Gl::CLIENT_ACTIVE_TEXTURE = GL_CLIENT_ACTIVE_TEXTURE;
const ATD::Gl::Enum ATD::Gl::MAX_TEXTURE_UNITS = GL_MAX_TEXTURE_UNITS;
/* texture_cube_map */
const ATD::Gl::Enum ATD::Gl::NORMAL_MAP = GL_NORMAL_MAP;
const ATD::Gl::Enum ATD::Gl::REFLECTION_MAP = GL_REFLECTION_MAP;
const ATD::Gl::Enum ATD::Gl::TEXTURE_CUBE_MAP = GL_TEXTURE_CUBE_MAP;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BINDING_CUBE_MAP = 
	GL_TEXTURE_BINDING_CUBE_MAP;
const ATD::Gl::Enum ATD::Gl::TEXTURE_CUBE_MAP_POSITIVE_X = 
	GL_TEXTURE_CUBE_MAP_POSITIVE_X;
const ATD::Gl::Enum ATD::Gl::TEXTURE_CUBE_MAP_NEGATIVE_X = 
	GL_TEXTURE_CUBE_MAP_NEGATIVE_X;
const ATD::Gl::Enum ATD::Gl::TEXTURE_CUBE_MAP_POSITIVE_Y = 
	GL_TEXTURE_CUBE_MAP_POSITIVE_Y;
const ATD::Gl::Enum ATD::Gl::TEXTURE_CUBE_MAP_NEGATIVE_Y = 
	GL_TEXTURE_CUBE_MAP_NEGATIVE_Y;
const ATD::Gl::Enum ATD::Gl::TEXTURE_CUBE_MAP_POSITIVE_Z = 
	GL_TEXTURE_CUBE_MAP_POSITIVE_Z;
const ATD::Gl::Enum ATD::Gl::TEXTURE_CUBE_MAP_NEGATIVE_Z = 
	GL_TEXTURE_CUBE_MAP_NEGATIVE_Z;
const ATD::Gl::Enum ATD::Gl::PROXY_TEXTURE_CUBE_MAP = 
	GL_PROXY_TEXTURE_CUBE_MAP;
const ATD::Gl::Enum ATD::Gl::MAX_CUBE_MAP_TEXTURE_SIZE = 
	GL_MAX_CUBE_MAP_TEXTURE_SIZE;
/* texture_compression */
const ATD::Gl::Enum ATD::Gl::COMPRESSED_ALPHA = GL_COMPRESSED_ALPHA;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_LUMINANCE = GL_COMPRESSED_LUMINANCE;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_LUMINANCE_ALPHA = 
	GL_COMPRESSED_LUMINANCE_ALPHA;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_INTENSITY = GL_COMPRESSED_INTENSITY;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_RGB = GL_COMPRESSED_RGB;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_RGBA = GL_COMPRESSED_RGBA;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COMPRESSION_HINT = 
	GL_TEXTURE_COMPRESSION_HINT;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COMPRESSED_IMAGE_SIZE = 
	GL_TEXTURE_COMPRESSED_IMAGE_SIZE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COMPRESSED = GL_TEXTURE_COMPRESSED;
const ATD::Gl::Enum ATD::Gl::NUM_COMPRESSED_TEXTURE_FORMATS = 
	GL_NUM_COMPRESSED_TEXTURE_FORMATS;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_TEXTURE_FORMATS = 
	GL_COMPRESSED_TEXTURE_FORMATS;
/* multisample */
const ATD::Gl::Enum ATD::Gl::MULTISAMPLE = GL_MULTISAMPLE;
const ATD::Gl::Enum ATD::Gl::SAMPLE_ALPHA_TO_COVERAGE = 
	GL_SAMPLE_ALPHA_TO_COVERAGE;
const ATD::Gl::Enum ATD::Gl::SAMPLE_ALPHA_TO_ONE = GL_SAMPLE_ALPHA_TO_ONE;
const ATD::Gl::Enum ATD::Gl::SAMPLE_COVERAGE = GL_SAMPLE_COVERAGE;
const ATD::Gl::Enum ATD::Gl::SAMPLE_BUFFERS = GL_SAMPLE_BUFFERS;
const ATD::Gl::Enum ATD::Gl::SAMPLES = GL_SAMPLES;
const ATD::Gl::Enum ATD::Gl::SAMPLE_COVERAGE_VALUE = GL_SAMPLE_COVERAGE_VALUE;
const ATD::Gl::Enum ATD::Gl::SAMPLE_COVERAGE_INVERT = 
	GL_SAMPLE_COVERAGE_INVERT;
const ATD::Gl::Bitfield ATD::Gl::MULTISAMPLE_BIT = GL_MULTISAMPLE_BIT;
/* transpose_matrix */
const ATD::Gl::Enum ATD::Gl::TRANSPOSE_MODELVIEW_MATRIX = 
	GL_TRANSPOSE_MODELVIEW_MATRIX;
const ATD::Gl::Enum ATD::Gl::TRANSPOSE_PROJECTION_MATRIX = 
	GL_TRANSPOSE_PROJECTION_MATRIX;
const ATD::Gl::Enum ATD::Gl::TRANSPOSE_TEXTURE_MATRIX = 
	GL_TRANSPOSE_TEXTURE_MATRIX;
const ATD::Gl::Enum ATD::Gl::TRANSPOSE_COLOR_MATRIX = 
	GL_TRANSPOSE_COLOR_MATRIX;
/* texture_env_combine */
const ATD::Gl::Enum ATD::Gl::COMBINE = GL_COMBINE;
const ATD::Gl::Enum ATD::Gl::COMBINE_RGB = GL_COMBINE_RGB;
const ATD::Gl::Enum ATD::Gl::COMBINE_ALPHA = GL_COMBINE_ALPHA;
const ATD::Gl::Enum ATD::Gl::SOURCE0_RGB = GL_SOURCE0_RGB;
const ATD::Gl::Enum ATD::Gl::SOURCE1_RGB = GL_SOURCE1_RGB;
const ATD::Gl::Enum ATD::Gl::SOURCE2_RGB = GL_SOURCE2_RGB;
const ATD::Gl::Enum ATD::Gl::SOURCE0_ALPHA = GL_SOURCE0_ALPHA;
const ATD::Gl::Enum ATD::Gl::SOURCE1_ALPHA = GL_SOURCE1_ALPHA;
const ATD::Gl::Enum ATD::Gl::SOURCE2_ALPHA = GL_SOURCE2_ALPHA;
const ATD::Gl::Enum ATD::Gl::OPERAND0_RGB = GL_OPERAND0_RGB;
const ATD::Gl::Enum ATD::Gl::OPERAND1_RGB = GL_OPERAND1_RGB;
const ATD::Gl::Enum ATD::Gl::OPERAND2_RGB = GL_OPERAND2_RGB;
const ATD::Gl::Enum ATD::Gl::OPERAND0_ALPHA = GL_OPERAND0_ALPHA;
const ATD::Gl::Enum ATD::Gl::OPERAND1_ALPHA = GL_OPERAND1_ALPHA;
const ATD::Gl::Enum ATD::Gl::OPERAND2_ALPHA = GL_OPERAND2_ALPHA;
const ATD::Gl::Enum ATD::Gl::RGB_SCALE = GL_RGB_SCALE;
const ATD::Gl::Enum ATD::Gl::ADD_SIGNED = GL_ADD_SIGNED;
const ATD::Gl::Enum ATD::Gl::INTERPOLATE = GL_INTERPOLATE;
const ATD::Gl::Enum ATD::Gl::SUBTRACT = GL_SUBTRACT;
const ATD::Gl::Enum ATD::Gl::CONSTANT = GL_CONSTANT;
const ATD::Gl::Enum ATD::Gl::PRIMARY_COLOR = GL_PRIMARY_COLOR;
const ATD::Gl::Enum ATD::Gl::PREVIOUS = GL_PREVIOUS;
/* texture_env_dot3 */
const ATD::Gl::Enum ATD::Gl::DOT3_RGB = GL_DOT3_RGB;
const ATD::Gl::Enum ATD::Gl::DOT3_RGBA = GL_DOT3_RGBA;
/* texture_border_clamp */
const ATD::Gl::Enum ATD::Gl::CLAMP_TO_BORDER = GL_CLAMP_TO_BORDER;

/* OpenGL 1.5 */
const ATD::Gl::Enum ATD::Gl::BUFFER_SIZE = GL_BUFFER_SIZE;
const ATD::Gl::Enum ATD::Gl::BUFFER_USAGE = GL_BUFFER_USAGE;
const ATD::Gl::Enum ATD::Gl::QUERY_COUNTER_BITS = GL_QUERY_COUNTER_BITS;
const ATD::Gl::Enum ATD::Gl::CURRENT_QUERY = GL_CURRENT_QUERY;
const ATD::Gl::Enum ATD::Gl::QUERY_RESULT = GL_QUERY_RESULT;
const ATD::Gl::Enum ATD::Gl::QUERY_RESULT_AVAILABLE = 
	GL_QUERY_RESULT_AVAILABLE;
const ATD::Gl::Enum ATD::Gl::ARRAY_BUFFER = GL_ARRAY_BUFFER;
const ATD::Gl::Enum ATD::Gl::ELEMENT_ARRAY_BUFFER = GL_ELEMENT_ARRAY_BUFFER;
const ATD::Gl::Enum ATD::Gl::ARRAY_BUFFER_BINDING = GL_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::ELEMENT_ARRAY_BUFFER_BINDING = 
	GL_ELEMENT_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 
	GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::READ_ONLY = GL_READ_ONLY;
const ATD::Gl::Enum ATD::Gl::WRITE_ONLY = GL_WRITE_ONLY;
const ATD::Gl::Enum ATD::Gl::READ_WRITE = GL_READ_WRITE;
const ATD::Gl::Enum ATD::Gl::BUFFER_ACCESS = GL_BUFFER_ACCESS;
const ATD::Gl::Enum ATD::Gl::BUFFER_MAPPED = GL_BUFFER_MAPPED;
const ATD::Gl::Enum ATD::Gl::BUFFER_MAP_POINTER = GL_BUFFER_MAP_POINTER;
const ATD::Gl::Enum ATD::Gl::STREAM_DRAW = GL_STREAM_DRAW;
const ATD::Gl::Enum ATD::Gl::STREAM_READ = GL_STREAM_READ;
const ATD::Gl::Enum ATD::Gl::STREAM_COPY = GL_STREAM_COPY;
const ATD::Gl::Enum ATD::Gl::STATIC_DRAW = GL_STATIC_DRAW;
const ATD::Gl::Enum ATD::Gl::STATIC_READ = GL_STATIC_READ;
const ATD::Gl::Enum ATD::Gl::STATIC_COPY = GL_STATIC_COPY;
const ATD::Gl::Enum ATD::Gl::DYNAMIC_DRAW = GL_DYNAMIC_DRAW;
const ATD::Gl::Enum ATD::Gl::DYNAMIC_READ = GL_DYNAMIC_READ;
const ATD::Gl::Enum ATD::Gl::DYNAMIC_COPY = GL_DYNAMIC_COPY;
const ATD::Gl::Enum ATD::Gl::SAMPLES_PASSED = GL_SAMPLES_PASSED;
const ATD::Gl::Enum ATD::Gl::SRC1_ALPHA = GL_SRC1_ALPHA;
const ATD::Gl::Enum ATD::Gl::VERTEX_ARRAY_BUFFER_BINDING = 
	GL_VERTEX_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::NORMAL_ARRAY_BUFFER_BINDING = 
	GL_NORMAL_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::COLOR_ARRAY_BUFFER_BINDING = 
	GL_COLOR_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::INDEX_ARRAY_BUFFER_BINDING = 
	GL_INDEX_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::TEXTURE_COORD_ARRAY_BUFFER_BINDING = 
	GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::EDGE_FLAG_ARRAY_BUFFER_BINDING = 
	GL_EDGE_FLAG_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::SECONDARY_COLOR_ARRAY_BUFFER_BINDING = 
	GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::FOG_COORDINATE_ARRAY_BUFFER_BINDING = 
	GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::WEIGHT_ARRAY_BUFFER_BINDING = 
	GL_WEIGHT_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::FOG_COORD_SRC = GL_FOG_COORD_SRC;
const ATD::Gl::Enum ATD::Gl::FOG_COORD = GL_FOG_COORD;
const ATD::Gl::Enum ATD::Gl::CURRENT_FOG_COORD = GL_CURRENT_FOG_COORD;
const ATD::Gl::Enum ATD::Gl::FOG_COORD_ARRAY_TYPE = GL_FOG_COORD_ARRAY_TYPE;
const ATD::Gl::Enum ATD::Gl::FOG_COORD_ARRAY_STRIDE = 
	GL_FOG_COORD_ARRAY_STRIDE;
const ATD::Gl::Enum ATD::Gl::FOG_COORD_ARRAY_POINTER = 
	GL_FOG_COORD_ARRAY_POINTER;
const ATD::Gl::Enum ATD::Gl::FOG_COORD_ARRAY = GL_FOG_COORD_ARRAY;
const ATD::Gl::Enum ATD::Gl::FOG_COORD_ARRAY_BUFFER_BINDING = 
	GL_FOG_COORD_ARRAY_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::SRC0_RGB = GL_SRC0_RGB;
const ATD::Gl::Enum ATD::Gl::SRC1_RGB = GL_SRC1_RGB;
const ATD::Gl::Enum ATD::Gl::SRC2_RGB = GL_SRC2_RGB;
const ATD::Gl::Enum ATD::Gl::SRC0_ALPHA = GL_SRC0_ALPHA;
const ATD::Gl::Enum ATD::Gl::SRC2_ALPHA = GL_SRC2_ALPHA;

/* OpenGL 2.0 */
const ATD::Gl::Enum ATD::Gl::BLEND_EQUATION_RGB = GL_BLEND_EQUATION_RGB;
const ATD::Gl::Enum ATD::Gl::VERTEX_ATTRIB_ARRAY_ENABLED = 
	GL_VERTEX_ATTRIB_ARRAY_ENABLED;
const ATD::Gl::Enum ATD::Gl::VERTEX_ATTRIB_ARRAY_SIZE = 
	GL_VERTEX_ATTRIB_ARRAY_SIZE;
const ATD::Gl::Enum ATD::Gl::VERTEX_ATTRIB_ARRAY_STRIDE = 
	GL_VERTEX_ATTRIB_ARRAY_STRIDE;
const ATD::Gl::Enum ATD::Gl::VERTEX_ATTRIB_ARRAY_TYPE = 
	GL_VERTEX_ATTRIB_ARRAY_TYPE;
const ATD::Gl::Enum ATD::Gl::CURRENT_VERTEX_ATTRIB = GL_CURRENT_VERTEX_ATTRIB;
const ATD::Gl::Enum ATD::Gl::VERTEX_PROGRAM_POINT_SIZE = 
	GL_VERTEX_PROGRAM_POINT_SIZE;
const ATD::Gl::Enum ATD::Gl::VERTEX_ATTRIB_ARRAY_POINTER = 
	GL_VERTEX_ATTRIB_ARRAY_POINTER;
const ATD::Gl::Enum ATD::Gl::STENCIL_BACK_FUNC = GL_STENCIL_BACK_FUNC;
const ATD::Gl::Enum ATD::Gl::STENCIL_BACK_FAIL = GL_STENCIL_BACK_FAIL;
const ATD::Gl::Enum ATD::Gl::STENCIL_BACK_PASS_DEPTH_FAIL = 
	GL_STENCIL_BACK_PASS_DEPTH_FAIL;
const ATD::Gl::Enum ATD::Gl::STENCIL_BACK_PASS_DEPTH_PASS = 
	GL_STENCIL_BACK_PASS_DEPTH_PASS;
const ATD::Gl::Enum ATD::Gl::MAX_DRAW_BUFFERS = GL_MAX_DRAW_BUFFERS;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER0 = GL_DRAW_BUFFER0;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER1 = GL_DRAW_BUFFER1;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER2 = GL_DRAW_BUFFER2;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER3 = GL_DRAW_BUFFER3;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER4 = GL_DRAW_BUFFER4;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER5 = GL_DRAW_BUFFER5;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER6 = GL_DRAW_BUFFER6;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER7 = GL_DRAW_BUFFER7;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER8 = GL_DRAW_BUFFER8;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER9 = GL_DRAW_BUFFER9;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER10 = GL_DRAW_BUFFER10;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER11 = GL_DRAW_BUFFER11;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER12 = GL_DRAW_BUFFER12;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER13 = GL_DRAW_BUFFER13;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER14 = GL_DRAW_BUFFER14;
const ATD::Gl::Enum ATD::Gl::DRAW_BUFFER15 = GL_DRAW_BUFFER15;
const ATD::Gl::Enum ATD::Gl::BLEND_EQUATION_ALPHA = GL_BLEND_EQUATION_ALPHA;
const ATD::Gl::Enum ATD::Gl::MAX_VERTEX_ATTRIBS = GL_MAX_VERTEX_ATTRIBS;
const ATD::Gl::Enum ATD::Gl::VERTEX_ATTRIB_ARRAY_NORMALIZED = 
	GL_VERTEX_ATTRIB_ARRAY_NORMALIZED;
const ATD::Gl::Enum ATD::Gl::MAX_TEXTURE_IMAGE_UNITS = 
	GL_MAX_TEXTURE_IMAGE_UNITS;
const ATD::Gl::Enum ATD::Gl::FRAGMENT_SHADER = GL_FRAGMENT_SHADER;
const ATD::Gl::Enum ATD::Gl::VERTEX_SHADER = GL_VERTEX_SHADER;
const ATD::Gl::Enum ATD::Gl::MAX_FRAGMENT_UNIFORM_COMPONENTS = 
	GL_MAX_FRAGMENT_UNIFORM_COMPONENTS;
const ATD::Gl::Enum ATD::Gl::MAX_VERTEX_UNIFORM_COMPONENTS = 
	GL_MAX_VERTEX_UNIFORM_COMPONENTS;
const ATD::Gl::Enum ATD::Gl::MAX_VARYING_FLOATS = GL_MAX_VARYING_FLOATS;
const ATD::Gl::Enum ATD::Gl::MAX_VERTEX_TEXTURE_IMAGE_UNITS = 
	GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS;
const ATD::Gl::Enum ATD::Gl::MAX_COMBINED_TEXTURE_IMAGE_UNITS = 
	GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS;
const ATD::Gl::Enum ATD::Gl::SHADER_TYPE = GL_SHADER_TYPE;
const ATD::Gl::Enum ATD::Gl::FLOAT_VEC2 = GL_FLOAT_VEC2;
const ATD::Gl::Enum ATD::Gl::FLOAT_VEC3 = GL_FLOAT_VEC3;
const ATD::Gl::Enum ATD::Gl::FLOAT_VEC4 = GL_FLOAT_VEC4;
const ATD::Gl::Enum ATD::Gl::INT_VEC2 = GL_INT_VEC2;
const ATD::Gl::Enum ATD::Gl::INT_VEC3 = GL_INT_VEC3;
const ATD::Gl::Enum ATD::Gl::INT_VEC4 = GL_INT_VEC4;
const ATD::Gl::Enum ATD::Gl::BOOL = GL_BOOL;
const ATD::Gl::Enum ATD::Gl::BOOL_VEC2 = GL_BOOL_VEC2;
const ATD::Gl::Enum ATD::Gl::BOOL_VEC3 = GL_BOOL_VEC3;
const ATD::Gl::Enum ATD::Gl::BOOL_VEC4 = GL_BOOL_VEC4;
const ATD::Gl::Enum ATD::Gl::FLOAT_MAT2 = GL_FLOAT_MAT2;
const ATD::Gl::Enum ATD::Gl::FLOAT_MAT3 = GL_FLOAT_MAT3;
const ATD::Gl::Enum ATD::Gl::FLOAT_MAT4 = GL_FLOAT_MAT4;
const ATD::Gl::Enum ATD::Gl::SAMPLER_1D = GL_SAMPLER_1D;
const ATD::Gl::Enum ATD::Gl::SAMPLER_2D = GL_SAMPLER_2D;
const ATD::Gl::Enum ATD::Gl::SAMPLER_3D = GL_SAMPLER_3D;
const ATD::Gl::Enum ATD::Gl::SAMPLER_CUBE = GL_SAMPLER_CUBE;
const ATD::Gl::Enum ATD::Gl::SAMPLER_1D_SHADOW = GL_SAMPLER_1D_SHADOW;
const ATD::Gl::Enum ATD::Gl::SAMPLER_2D_SHADOW = GL_SAMPLER_2D_SHADOW;
const ATD::Gl::Enum ATD::Gl::DELETE_STATUS = GL_DELETE_STATUS;
const ATD::Gl::Enum ATD::Gl::COMPILE_STATUS = GL_COMPILE_STATUS;
const ATD::Gl::Enum ATD::Gl::LINK_STATUS = GL_LINK_STATUS;
const ATD::Gl::Enum ATD::Gl::VALIDATE_STATUS = GL_VALIDATE_STATUS;
const ATD::Gl::Enum ATD::Gl::INFO_LOG_LENGTH = GL_INFO_LOG_LENGTH;
const ATD::Gl::Enum ATD::Gl::ATTACHED_SHADERS = GL_ATTACHED_SHADERS;
const ATD::Gl::Enum ATD::Gl::ACTIVE_UNIFORMS = GL_ACTIVE_UNIFORMS;
const ATD::Gl::Enum ATD::Gl::ACTIVE_UNIFORM_MAX_LENGTH = 
	GL_ACTIVE_UNIFORM_MAX_LENGTH;
const ATD::Gl::Enum ATD::Gl::SHADER_SOURCE_LENGTH = GL_SHADER_SOURCE_LENGTH;
const ATD::Gl::Enum ATD::Gl::ACTIVE_ATTRIBUTES = GL_ACTIVE_ATTRIBUTES;
const ATD::Gl::Enum ATD::Gl::ACTIVE_ATTRIBUTE_MAX_LENGTH = 
	GL_ACTIVE_ATTRIBUTE_MAX_LENGTH;
const ATD::Gl::Enum ATD::Gl::FRAGMENT_SHADER_DERIVATIVE_HINT = 
	GL_FRAGMENT_SHADER_DERIVATIVE_HINT;
const ATD::Gl::Enum ATD::Gl::SHADING_LANGUAGE_VERSION = 
	GL_SHADING_LANGUAGE_VERSION;
const ATD::Gl::Enum ATD::Gl::CURRENT_PROGRAM = GL_CURRENT_PROGRAM;
const ATD::Gl::Enum ATD::Gl::POINT_SPRITE_COORD_ORIGIN = 
	GL_POINT_SPRITE_COORD_ORIGIN;
const ATD::Gl::Enum ATD::Gl::LOWER_LEFT = GL_LOWER_LEFT;
const ATD::Gl::Enum ATD::Gl::UPPER_LEFT = GL_UPPER_LEFT;
const ATD::Gl::Enum ATD::Gl::STENCIL_BACK_REF = GL_STENCIL_BACK_REF;
const ATD::Gl::Enum ATD::Gl::STENCIL_BACK_VALUE_MASK = 
	GL_STENCIL_BACK_VALUE_MASK;
const ATD::Gl::Enum ATD::Gl::STENCIL_BACK_WRITEMASK = 
	GL_STENCIL_BACK_WRITEMASK;
const ATD::Gl::Enum ATD::Gl::VERTEX_PROGRAM_TWO_SIDE = 
	GL_VERTEX_PROGRAM_TWO_SIDE;
const ATD::Gl::Enum ATD::Gl::POINT_SPRITE = GL_POINT_SPRITE;
const ATD::Gl::Enum ATD::Gl::COORD_REPLACE = GL_COORD_REPLACE;
const ATD::Gl::Enum ATD::Gl::MAX_TEXTURE_COORDS = GL_MAX_TEXTURE_COORDS;

/* OpenGL 2.1 */

const ATD::Gl::Enum ATD::Gl::PIXEL_PACK_BUFFER = GL_PIXEL_PACK_BUFFER;
const ATD::Gl::Enum ATD::Gl::PIXEL_UNPACK_BUFFER = GL_PIXEL_UNPACK_BUFFER;
const ATD::Gl::Enum ATD::Gl::PIXEL_PACK_BUFFER_BINDING = 
	GL_PIXEL_PACK_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::PIXEL_UNPACK_BUFFER_BINDING = 
	GL_PIXEL_UNPACK_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::FLOAT_MAT2x3 = GL_FLOAT_MAT2x3;
const ATD::Gl::Enum ATD::Gl::FLOAT_MAT2x4 = GL_FLOAT_MAT2x4;
const ATD::Gl::Enum ATD::Gl::FLOAT_MAT3x2 = GL_FLOAT_MAT3x2;
const ATD::Gl::Enum ATD::Gl::FLOAT_MAT3x4 = GL_FLOAT_MAT3x4;
const ATD::Gl::Enum ATD::Gl::FLOAT_MAT4x2 = GL_FLOAT_MAT4x2;
const ATD::Gl::Enum ATD::Gl::FLOAT_MAT4x3 = GL_FLOAT_MAT4x3;
const ATD::Gl::Enum ATD::Gl::SRGB = GL_SRGB;
const ATD::Gl::Enum ATD::Gl::SRGB8 = GL_SRGB8;
const ATD::Gl::Enum ATD::Gl::SRGB_ALPHA = GL_SRGB_ALPHA;
const ATD::Gl::Enum ATD::Gl::SRGB8_ALPHA8 = GL_SRGB8_ALPHA8;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_SRGB = GL_COMPRESSED_SRGB;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_SRGB_ALPHA = GL_COMPRESSED_SRGB_ALPHA;
const ATD::Gl::Enum ATD::Gl::CURRENT_RASTER_SECONDARY_COLOR = 
	GL_CURRENT_RASTER_SECONDARY_COLOR;
const ATD::Gl::Enum ATD::Gl::SLUMINANCE_ALPHA = GL_SLUMINANCE_ALPHA;
const ATD::Gl::Enum ATD::Gl::SLUMINANCE8_ALPHA8 = GL_SLUMINANCE8_ALPHA8;
const ATD::Gl::Enum ATD::Gl::SLUMINANCE = GL_SLUMINANCE;
const ATD::Gl::Enum ATD::Gl::SLUMINANCE8 = GL_SLUMINANCE8;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_SLUMINANCE = GL_COMPRESSED_SLUMINANCE;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_SLUMINANCE_ALPHA = 
	GL_COMPRESSED_SLUMINANCE_ALPHA;

/* OpenGL 3.0 */
const ATD::Gl::Enum ATD::Gl::COMPARE_REF_TO_TEXTURE = 
	GL_COMPARE_REF_TO_TEXTURE;
const ATD::Gl::Enum ATD::Gl::CLIP_DISTANCE0 = GL_CLIP_DISTANCE0;
const ATD::Gl::Enum ATD::Gl::CLIP_DISTANCE1 = GL_CLIP_DISTANCE1;
const ATD::Gl::Enum ATD::Gl::CLIP_DISTANCE2 = GL_CLIP_DISTANCE2;
const ATD::Gl::Enum ATD::Gl::CLIP_DISTANCE3 = GL_CLIP_DISTANCE3;
const ATD::Gl::Enum ATD::Gl::CLIP_DISTANCE4 = GL_CLIP_DISTANCE4;
const ATD::Gl::Enum ATD::Gl::CLIP_DISTANCE5 = GL_CLIP_DISTANCE5;
const ATD::Gl::Enum ATD::Gl::CLIP_DISTANCE6 = GL_CLIP_DISTANCE6;
const ATD::Gl::Enum ATD::Gl::CLIP_DISTANCE7 = GL_CLIP_DISTANCE7;
const ATD::Gl::Enum ATD::Gl::MAX_CLIP_DISTANCES = GL_MAX_CLIP_DISTANCES;
const ATD::Gl::Enum ATD::Gl::MAJOR_VERSION = GL_MAJOR_VERSION;
const ATD::Gl::Enum ATD::Gl::MINOR_VERSION = GL_MINOR_VERSION;
const ATD::Gl::Enum ATD::Gl::NUM_EXTENSIONS = GL_NUM_EXTENSIONS;
const ATD::Gl::Enum ATD::Gl::CONTEXT_FLAGS = GL_CONTEXT_FLAGS;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_RED = GL_COMPRESSED_RED;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_RG = GL_COMPRESSED_RG;
const ATD::Gl::Enum ATD::Gl::CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 
	GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT;
const ATD::Gl::Enum ATD::Gl::RGBA32F = GL_RGBA32F;
const ATD::Gl::Enum ATD::Gl::RGB32F = GL_RGB32F;
const ATD::Gl::Enum ATD::Gl::RGBA16F = GL_RGBA16F;
const ATD::Gl::Enum ATD::Gl::RGB16F = GL_RGB16F;
const ATD::Gl::Enum ATD::Gl::VERTEX_ATTRIB_ARRAY_INTEGER = 
	GL_VERTEX_ATTRIB_ARRAY_INTEGER;
const ATD::Gl::Enum ATD::Gl::MAX_ARRAY_TEXTURE_LAYERS = 
	GL_MAX_ARRAY_TEXTURE_LAYERS;
const ATD::Gl::Enum ATD::Gl::MIN_PROGRAM_TEXEL_OFFSET = 
	GL_MIN_PROGRAM_TEXEL_OFFSET;
const ATD::Gl::Enum ATD::Gl::MAX_PROGRAM_TEXEL_OFFSET = 
	GL_MAX_PROGRAM_TEXEL_OFFSET;
const ATD::Gl::Enum ATD::Gl::CLAMP_READ_COLOR = GL_CLAMP_READ_COLOR;
const ATD::Gl::Enum ATD::Gl::FIXED_ONLY = GL_FIXED_ONLY;
const ATD::Gl::Enum ATD::Gl::MAX_VARYING_COMPONENTS = 
	GL_MAX_VARYING_COMPONENTS;
const ATD::Gl::Enum ATD::Gl::TEXTURE_1D_ARRAY = GL_TEXTURE_1D_ARRAY;
const ATD::Gl::Enum ATD::Gl::PROXY_TEXTURE_1D_ARRAY = 
	GL_PROXY_TEXTURE_1D_ARRAY;
const ATD::Gl::Enum ATD::Gl::TEXTURE_2D_ARRAY = GL_TEXTURE_2D_ARRAY;
const ATD::Gl::Enum ATD::Gl::PROXY_TEXTURE_2D_ARRAY = 
	GL_PROXY_TEXTURE_2D_ARRAY;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BINDING_1D_ARRAY = 
	GL_TEXTURE_BINDING_1D_ARRAY;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BINDING_2D_ARRAY = 
	GL_TEXTURE_BINDING_2D_ARRAY;
const ATD::Gl::Enum ATD::Gl::R11F_G11F_B10F = GL_R11F_G11F_B10F;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_10F_11F_11F_REV = 
	GL_UNSIGNED_INT_10F_11F_11F_REV;
const ATD::Gl::Enum ATD::Gl::RGB9_E5 = GL_RGB9_E5;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_5_9_9_9_REV = 
	GL_UNSIGNED_INT_5_9_9_9_REV;
const ATD::Gl::Enum ATD::Gl::TEXTURE_SHARED_SIZE = GL_TEXTURE_SHARED_SIZE;
const ATD::Gl::Enum ATD::Gl::TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 
	GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH;
const ATD::Gl::Enum ATD::Gl::TRANSFORM_FEEDBACK_BUFFER_MODE = 
	GL_TRANSFORM_FEEDBACK_BUFFER_MODE;
const ATD::Gl::Enum ATD::Gl::MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 
	GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS;
const ATD::Gl::Enum ATD::Gl::TRANSFORM_FEEDBACK_VARYINGS = 
	GL_TRANSFORM_FEEDBACK_VARYINGS;
const ATD::Gl::Enum ATD::Gl::TRANSFORM_FEEDBACK_BUFFER_START = 
	GL_TRANSFORM_FEEDBACK_BUFFER_START;
const ATD::Gl::Enum ATD::Gl::TRANSFORM_FEEDBACK_BUFFER_SIZE = 
	GL_TRANSFORM_FEEDBACK_BUFFER_SIZE;
const ATD::Gl::Enum ATD::Gl::PRIMITIVES_GENERATED = GL_PRIMITIVES_GENERATED;
const ATD::Gl::Enum ATD::Gl::TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 
	GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN;
const ATD::Gl::Enum ATD::Gl::RASTERIZER_DISCARD = GL_RASTERIZER_DISCARD;
const ATD::Gl::Enum ATD::Gl::MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 
	GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS;
const ATD::Gl::Enum ATD::Gl::MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 
	GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS;
const ATD::Gl::Enum ATD::Gl::INTERLEAVED_ATTRIBS = GL_INTERLEAVED_ATTRIBS;
const ATD::Gl::Enum ATD::Gl::SEPARATE_ATTRIBS = GL_SEPARATE_ATTRIBS;
const ATD::Gl::Enum ATD::Gl::TRANSFORM_FEEDBACK_BUFFER = 
	GL_TRANSFORM_FEEDBACK_BUFFER;
const ATD::Gl::Enum ATD::Gl::TRANSFORM_FEEDBACK_BUFFER_BINDING = 
	GL_TRANSFORM_FEEDBACK_BUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::RGBA32UI = GL_RGBA32UI;
const ATD::Gl::Enum ATD::Gl::RGB32UI = GL_RGB32UI;
const ATD::Gl::Enum ATD::Gl::RGBA16UI = GL_RGBA16UI;
const ATD::Gl::Enum ATD::Gl::RGB16UI = GL_RGB16UI;
const ATD::Gl::Enum ATD::Gl::RGBA8UI = GL_RGBA8UI;
const ATD::Gl::Enum ATD::Gl::RGB8UI = GL_RGB8UI;
const ATD::Gl::Enum ATD::Gl::RGBA32I = GL_RGBA32I;
const ATD::Gl::Enum ATD::Gl::RGB32I = GL_RGB32I;
const ATD::Gl::Enum ATD::Gl::RGBA16I = GL_RGBA16I;
const ATD::Gl::Enum ATD::Gl::RGB16I = GL_RGB16I;
const ATD::Gl::Enum ATD::Gl::RGBA8I = GL_RGBA8I;
const ATD::Gl::Enum ATD::Gl::RGB8I = GL_RGB8I;
const ATD::Gl::Enum ATD::Gl::RED_INTEGER = GL_RED_INTEGER;
const ATD::Gl::Enum ATD::Gl::GREEN_INTEGER = GL_GREEN_INTEGER;
const ATD::Gl::Enum ATD::Gl::BLUE_INTEGER = GL_BLUE_INTEGER;
const ATD::Gl::Enum ATD::Gl::RGB_INTEGER = GL_RGB_INTEGER;
const ATD::Gl::Enum ATD::Gl::RGBA_INTEGER = GL_RGBA_INTEGER;
const ATD::Gl::Enum ATD::Gl::BGR_INTEGER = GL_BGR_INTEGER;
const ATD::Gl::Enum ATD::Gl::BGRA_INTEGER = GL_BGRA_INTEGER;
const ATD::Gl::Enum ATD::Gl::SAMPLER_1D_ARRAY = GL_SAMPLER_1D_ARRAY;
const ATD::Gl::Enum ATD::Gl::SAMPLER_2D_ARRAY = GL_SAMPLER_2D_ARRAY;
const ATD::Gl::Enum ATD::Gl::SAMPLER_1D_ARRAY_SHADOW = 
	GL_SAMPLER_1D_ARRAY_SHADOW;
const ATD::Gl::Enum ATD::Gl::SAMPLER_2D_ARRAY_SHADOW = 
	GL_SAMPLER_2D_ARRAY_SHADOW;
const ATD::Gl::Enum ATD::Gl::SAMPLER_CUBE_SHADOW = GL_SAMPLER_CUBE_SHADOW;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_VEC2 = GL_UNSIGNED_INT_VEC2;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_VEC3 = GL_UNSIGNED_INT_VEC3;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_VEC4 = GL_UNSIGNED_INT_VEC4;
const ATD::Gl::Enum ATD::Gl::INT_SAMPLER_1D = GL_INT_SAMPLER_1D;
const ATD::Gl::Enum ATD::Gl::INT_SAMPLER_2D = GL_INT_SAMPLER_2D;
const ATD::Gl::Enum ATD::Gl::INT_SAMPLER_3D = GL_INT_SAMPLER_3D;
const ATD::Gl::Enum ATD::Gl::INT_SAMPLER_CUBE = GL_INT_SAMPLER_CUBE;
const ATD::Gl::Enum ATD::Gl::INT_SAMPLER_1D_ARRAY = GL_INT_SAMPLER_1D_ARRAY;
const ATD::Gl::Enum ATD::Gl::INT_SAMPLER_2D_ARRAY = GL_INT_SAMPLER_2D_ARRAY;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_SAMPLER_1D = 
	GL_UNSIGNED_INT_SAMPLER_1D;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_SAMPLER_2D = 
	GL_UNSIGNED_INT_SAMPLER_2D;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_SAMPLER_3D = 
	GL_UNSIGNED_INT_SAMPLER_3D;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_SAMPLER_CUBE = 
	GL_UNSIGNED_INT_SAMPLER_CUBE;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_SAMPLER_1D_ARRAY = 
	GL_UNSIGNED_INT_SAMPLER_1D_ARRAY;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_SAMPLER_2D_ARRAY = 
	GL_UNSIGNED_INT_SAMPLER_2D_ARRAY;
const ATD::Gl::Enum ATD::Gl::QUERY_WAIT = GL_QUERY_WAIT;
const ATD::Gl::Enum ATD::Gl::QUERY_NO_WAIT = GL_QUERY_NO_WAIT;
const ATD::Gl::Enum ATD::Gl::QUERY_BY_REGION_WAIT = GL_QUERY_BY_REGION_WAIT;
const ATD::Gl::Enum ATD::Gl::QUERY_BY_REGION_NO_WAIT = 
	GL_QUERY_BY_REGION_NO_WAIT;
const ATD::Gl::Enum ATD::Gl::BUFFER_ACCESS_FLAGS = GL_BUFFER_ACCESS_FLAGS;
const ATD::Gl::Enum ATD::Gl::BUFFER_MAP_LENGTH = GL_BUFFER_MAP_LENGTH;
const ATD::Gl::Enum ATD::Gl::BUFFER_MAP_OFFSET = GL_BUFFER_MAP_OFFSET;
const ATD::Gl::Enum ATD::Gl::DEPTH_COMPONENT32F = GL_DEPTH_COMPONENT32F;
const ATD::Gl::Enum ATD::Gl::DEPTH32F_STENCIL8 = GL_DEPTH32F_STENCIL8;
const ATD::Gl::Enum ATD::Gl::FLOAT_32_UNSIGNED_INT_24_8_REV = 
	GL_FLOAT_32_UNSIGNED_INT_24_8_REV;
const ATD::Gl::Enum ATD::Gl::INVALID_FRAMEBUFFER_OPERATION = 
	GL_INVALID_FRAMEBUFFER_OPERATION;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 
	GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 
	GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_RED_SIZE = 
	GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 
	GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 
	GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 
	GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 
	GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 
	GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_DEFAULT = GL_FRAMEBUFFER_DEFAULT;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_UNDEFINED = GL_FRAMEBUFFER_UNDEFINED;
const ATD::Gl::Enum ATD::Gl::DEPTH_STENCIL_ATTACHMENT = 
	GL_DEPTH_STENCIL_ATTACHMENT;
const ATD::Gl::Enum ATD::Gl::MAX_RENDERBUFFER_SIZE = GL_MAX_RENDERBUFFER_SIZE;
const ATD::Gl::Enum ATD::Gl::DEPTH_STENCIL = GL_DEPTH_STENCIL;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_INT_24_8 = GL_UNSIGNED_INT_24_8;
const ATD::Gl::Enum ATD::Gl::DEPTH24_STENCIL8 = GL_DEPTH24_STENCIL8;
const ATD::Gl::Enum ATD::Gl::TEXTURE_STENCIL_SIZE = GL_TEXTURE_STENCIL_SIZE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_RED_TYPE = GL_TEXTURE_RED_TYPE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_GREEN_TYPE = GL_TEXTURE_GREEN_TYPE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_BLUE_TYPE = GL_TEXTURE_BLUE_TYPE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_ALPHA_TYPE = GL_TEXTURE_ALPHA_TYPE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_DEPTH_TYPE = GL_TEXTURE_DEPTH_TYPE;
const ATD::Gl::Enum ATD::Gl::UNSIGNED_NORMALIZED = GL_UNSIGNED_NORMALIZED;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_BINDING = GL_FRAMEBUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::DRAW_FRAMEBUFFER_BINDING = 
	GL_DRAW_FRAMEBUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_BINDING = GL_RENDERBUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::READ_FRAMEBUFFER = GL_READ_FRAMEBUFFER;
const ATD::Gl::Enum ATD::Gl::DRAW_FRAMEBUFFER = GL_DRAW_FRAMEBUFFER;
const ATD::Gl::Enum ATD::Gl::READ_FRAMEBUFFER_BINDING = 
	GL_READ_FRAMEBUFFER_BINDING;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_SAMPLES = GL_RENDERBUFFER_SAMPLES;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 
	GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 
	GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 
	GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 
	GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 
	GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_COMPLETE = GL_FRAMEBUFFER_COMPLETE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 
	GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 
	GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 
	GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 
	GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_UNSUPPORTED = 
	GL_FRAMEBUFFER_UNSUPPORTED;
const ATD::Gl::Enum ATD::Gl::MAX_COLOR_ATTACHMENTS = GL_MAX_COLOR_ATTACHMENTS;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT0 = GL_COLOR_ATTACHMENT0;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT1 = GL_COLOR_ATTACHMENT1;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT2 = GL_COLOR_ATTACHMENT2;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT3 = GL_COLOR_ATTACHMENT3;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT4 = GL_COLOR_ATTACHMENT4;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT5 = GL_COLOR_ATTACHMENT5;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT6 = GL_COLOR_ATTACHMENT6;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT7 = GL_COLOR_ATTACHMENT7;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT8 = GL_COLOR_ATTACHMENT8;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT9 = GL_COLOR_ATTACHMENT9;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT10 = GL_COLOR_ATTACHMENT10;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT11 = GL_COLOR_ATTACHMENT11;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT12 = GL_COLOR_ATTACHMENT12;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT13 = GL_COLOR_ATTACHMENT13;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT14 = GL_COLOR_ATTACHMENT14;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT15 = GL_COLOR_ATTACHMENT15;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT16 = GL_COLOR_ATTACHMENT16;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT17 = GL_COLOR_ATTACHMENT17;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT18 = GL_COLOR_ATTACHMENT18;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT19 = GL_COLOR_ATTACHMENT19;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT20 = GL_COLOR_ATTACHMENT20;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT21 = GL_COLOR_ATTACHMENT21;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT22 = GL_COLOR_ATTACHMENT22;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT23 = GL_COLOR_ATTACHMENT23;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT24 = GL_COLOR_ATTACHMENT24;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT25 = GL_COLOR_ATTACHMENT25;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT26 = GL_COLOR_ATTACHMENT26;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT27 = GL_COLOR_ATTACHMENT27;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT28 = GL_COLOR_ATTACHMENT28;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT29 = GL_COLOR_ATTACHMENT29;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT30 = GL_COLOR_ATTACHMENT30;
const ATD::Gl::Enum ATD::Gl::COLOR_ATTACHMENT31 = GL_COLOR_ATTACHMENT31;
const ATD::Gl::Enum ATD::Gl::DEPTH_ATTACHMENT = GL_DEPTH_ATTACHMENT;
const ATD::Gl::Enum ATD::Gl::STENCIL_ATTACHMENT = GL_STENCIL_ATTACHMENT;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER = GL_FRAMEBUFFER;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER = GL_RENDERBUFFER;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_WIDTH = GL_RENDERBUFFER_WIDTH;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_HEIGHT = GL_RENDERBUFFER_HEIGHT;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_INTERNAL_FORMAT = 
	GL_RENDERBUFFER_INTERNAL_FORMAT;
const ATD::Gl::Enum ATD::Gl::STENCIL_INDEX1 = GL_STENCIL_INDEX1;
const ATD::Gl::Enum ATD::Gl::STENCIL_INDEX4 = GL_STENCIL_INDEX4;
const ATD::Gl::Enum ATD::Gl::STENCIL_INDEX8 = GL_STENCIL_INDEX8;
const ATD::Gl::Enum ATD::Gl::STENCIL_INDEX16 = GL_STENCIL_INDEX16;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_RED_SIZE = GL_RENDERBUFFER_RED_SIZE;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_GREEN_SIZE = 
	GL_RENDERBUFFER_GREEN_SIZE;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_BLUE_SIZE = 
	GL_RENDERBUFFER_BLUE_SIZE;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_ALPHA_SIZE = 
	GL_RENDERBUFFER_ALPHA_SIZE;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_DEPTH_SIZE = 
	GL_RENDERBUFFER_DEPTH_SIZE;
const ATD::Gl::Enum ATD::Gl::RENDERBUFFER_STENCIL_SIZE = 
	GL_RENDERBUFFER_STENCIL_SIZE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 
	GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE;
const ATD::Gl::Enum ATD::Gl::MAX_SAMPLES = GL_MAX_SAMPLES;
const ATD::Gl::Enum ATD::Gl::INDEX = GL_INDEX;
const ATD::Gl::Enum ATD::Gl::TEXTURE_LUMINANCE_TYPE = 
	GL_TEXTURE_LUMINANCE_TYPE;
const ATD::Gl::Enum ATD::Gl::TEXTURE_INTENSITY_TYPE = 
	GL_TEXTURE_INTENSITY_TYPE;
const ATD::Gl::Enum ATD::Gl::FRAMEBUFFER_SRGB = GL_FRAMEBUFFER_SRGB;
const ATD::Gl::Enum ATD::Gl::HALF_FLOAT = GL_HALF_FLOAT;
const ATD::Gl::Enum ATD::Gl::MAP_READ_BIT = GL_MAP_READ_BIT;
const ATD::Gl::Enum ATD::Gl::MAP_WRITE_BIT = GL_MAP_WRITE_BIT;
const ATD::Gl::Enum ATD::Gl::MAP_INVALIDATE_RANGE_BIT = 
	GL_MAP_INVALIDATE_RANGE_BIT;
const ATD::Gl::Enum ATD::Gl::MAP_INVALIDATE_BUFFER_BIT = 
	GL_MAP_INVALIDATE_BUFFER_BIT;
const ATD::Gl::Enum ATD::Gl::MAP_FLUSH_EXPLICIT_BIT = 
	GL_MAP_FLUSH_EXPLICIT_BIT;
const ATD::Gl::Enum ATD::Gl::MAP_UNSYNCHRONIZED_BIT = 
	GL_MAP_UNSYNCHRONIZED_BIT;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_RED_RGTC1 = GL_COMPRESSED_RED_RGTC1;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_SIGNED_RED_RGTC1 = 
	GL_COMPRESSED_SIGNED_RED_RGTC1;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_RG_RGTC2 = GL_COMPRESSED_RG_RGTC2;
const ATD::Gl::Enum ATD::Gl::COMPRESSED_SIGNED_RG_RGTC2 = 
	GL_COMPRESSED_SIGNED_RG_RGTC2;
const ATD::Gl::Enum ATD::Gl::RG = GL_RG;
const ATD::Gl::Enum ATD::Gl::RG_INTEGER = GL_RG_INTEGER;
const ATD::Gl::Enum ATD::Gl::R8 = GL_R8;
const ATD::Gl::Enum ATD::Gl::R16 = GL_R16;
const ATD::Gl::Enum ATD::Gl::RG8 = GL_RG8;
const ATD::Gl::Enum ATD::Gl::RG16 = GL_RG16;
const ATD::Gl::Enum ATD::Gl::R16F = GL_R16F;
const ATD::Gl::Enum ATD::Gl::R32F = GL_R32F;
const ATD::Gl::Enum ATD::Gl::RG16F = GL_RG16F;
const ATD::Gl::Enum ATD::Gl::RG32F = GL_RG32F;
const ATD::Gl::Enum ATD::Gl::R8I = GL_R8I;
const ATD::Gl::Enum ATD::Gl::R8UI = GL_R8UI;
const ATD::Gl::Enum ATD::Gl::R16I = GL_R16I;
const ATD::Gl::Enum ATD::Gl::R16UI = GL_R16UI;
const ATD::Gl::Enum ATD::Gl::R32I = GL_R32I;
const ATD::Gl::Enum ATD::Gl::R32UI = GL_R32UI;
const ATD::Gl::Enum ATD::Gl::RG8I = GL_RG8I;
const ATD::Gl::Enum ATD::Gl::RG8UI = GL_RG8UI;
const ATD::Gl::Enum ATD::Gl::RG16I = GL_RG16I;
const ATD::Gl::Enum ATD::Gl::RG16UI = GL_RG16UI;
const ATD::Gl::Enum ATD::Gl::RG32I = GL_RG32I;
const ATD::Gl::Enum ATD::Gl::RG32UI = GL_RG32UI;
const ATD::Gl::Enum ATD::Gl::VERTEX_ARRAY_BINDING = GL_VERTEX_ARRAY_BINDING;
const ATD::Gl::Enum ATD::Gl::CLAMP_VERTEX_COLOR = GL_CLAMP_VERTEX_COLOR;
const ATD::Gl::Enum ATD::Gl::CLAMP_FRAGMENT_COLOR = GL_CLAMP_FRAGMENT_COLOR;
const ATD::Gl::Enum ATD::Gl::ALPHA_INTEGER = GL_ALPHA_INTEGER;


/* ATD::Gl */

ATD::Gl::Gl()
{
	std::vector<std::string> failures;

	getError = reinterpret_cast<GetErrorFunc *>(_loadFunction(
				"glGetError", failures));

	viewport = reinterpret_cast<ViewportFunc *>(_loadFunction(
				"glViewport", failures));
	clear = reinterpret_cast<ClearFunc *>(_loadFunction(
				"glClear", failures));
	getBooleanv = reinterpret_cast<GetBooleanvFunc *>(_loadFunction(
				"glGetBooleanv", failures));
	getFloatv = reinterpret_cast<GetFloatvFunc *>(_loadFunction(
				"glGetFloatv", failures));
	getIntegerv = reinterpret_cast<GetIntegervFunc *>(_loadFunction(
				"glGetIntegerv", failures));

	genBuffers = reinterpret_cast<GenBuffersFunc *>(_loadFunction(
				"glGenBuffers", failures));
	deleteBuffers = reinterpret_cast<DeleteBuffersFunc *>(_loadFunction(
				"glDeleteBuffers", failures));
	bindBuffer = reinterpret_cast<BindBufferFunc *>(_loadFunction(
				"glBindBuffer", failures));
	bufferData = reinterpret_cast<BufferDataFunc *>(_loadFunction(
				"glBufferData", failures));
	mapBuffer = reinterpret_cast<MapBufferFunc *>(_loadFunction(
				"glMapBuffer", failures));
	unmapBuffer = reinterpret_cast<UnmapBufferFunc *>(_loadFunction(
				"glUnmapBuffer", failures));
	vertexAttribPointer = 
		reinterpret_cast<VertexAttribPointerFunc *>(_loadFunction(
					"glVertexAttribPointer", failures));
	enableVertexAttribArray = 
		reinterpret_cast<EnableVertexAttribArrayFunc *>(_loadFunction(
					"glEnableVertexAttribArray", failures));
	disableVertexAttribArray = 
		reinterpret_cast<DisableVertexAttribArrayFunc *>(_loadFunction(
					"glDisableVertexAttribArray", failures));
	drawArrays = reinterpret_cast<DrawArraysFunc *>(_loadFunction(
				"glDrawArrays", failures));
	drawElements = reinterpret_cast<DrawElementsFunc *>(_loadFunction(
				"glDrawElements", failures));

	createShader = reinterpret_cast<CreateShaderFunc *>(_loadFunction(
				"glCreateShader", failures));
	deleteShader = reinterpret_cast<DeleteShaderFunc *>(_loadFunction(
				"glDeleteShader", failures));
	shaderSource = reinterpret_cast<ShaderSourceFunc *>(_loadFunction(
				"glShaderSource", failures));
	compileShader = reinterpret_cast<CompileShaderFunc *>(_loadFunction(
				"glCompileShader", failures));
	attachShader = reinterpret_cast<AttachShaderFunc *>(_loadFunction(
				"glAttachShader", failures));
	getShaderiv = reinterpret_cast<GetShaderivFunc *>(_loadFunction(
				"glGetShaderiv", failures));
	getShaderInfoLog = 
		reinterpret_cast<GetShaderInfoLogFunc *>(_loadFunction(
					"glGetShaderInfoLog", failures));

	createProgram = reinterpret_cast<CreateProgramFunc *>(_loadFunction(
				"glCreateProgram", failures));
	deleteProgram = reinterpret_cast<DeleteProgramFunc *>(_loadFunction(
				"glDeleteProgram", failures));
	linkProgram = reinterpret_cast<LinkProgramFunc *>(_loadFunction(
				"glLinkProgram", failures));
	validateProgram = reinterpret_cast<ValidateProgramFunc *>(_loadFunction(
				"glValidateProgram", failures));
	useProgram = reinterpret_cast<UseProgramFunc *>(_loadFunction(
				"glUseProgram", failures));
	getProgramiv = reinterpret_cast<GetProgramivFunc *>(_loadFunction(
				"glGetProgramiv", failures));
	getProgramInfoLog = 
		reinterpret_cast<GetProgramInfoLogFunc *>(_loadFunction(
					"glGetProgramInfoLog", failures));

	getUniformLocation = 
		reinterpret_cast<GetUniformLocationFunc *>(_loadFunction(
					"glGetUniformLocation", failures));
	getActiveUniform = 
		reinterpret_cast<GetActiveUniformFunc *>(_loadFunction(
					"glGetActiveUniform", failures));
	getActiveAttrib = 
		reinterpret_cast<GetActiveAttribFunc *>(_loadFunction(
					"glGetActiveAttrib", failures));
	uniform1f = reinterpret_cast<Uniform1fFunc *>(_loadFunction(
				"glUniform1f", failures));
	uniform2f = reinterpret_cast<Uniform2fFunc *>(_loadFunction(
				"glUniform2f", failures));
	uniform3f = reinterpret_cast<Uniform3fFunc *>(_loadFunction(
				"glUniform3f", failures));
	uniform4f = reinterpret_cast<Uniform4fFunc *>(_loadFunction(
				"glUniform4f", failures));
	uniform1i = reinterpret_cast<Uniform1iFunc *>(_loadFunction(
				"glUniform1i", failures));
	uniform2i = reinterpret_cast<Uniform2iFunc *>(_loadFunction(
				"glUniform2i", failures));
	uniform3i = reinterpret_cast<Uniform3iFunc *>(_loadFunction(
				"glUniform3i", failures));
	uniform4i = reinterpret_cast<Uniform4iFunc *>(_loadFunction(
				"glUniform4i", failures));
	uniform1fv = reinterpret_cast<Uniform1fvFunc *>(_loadFunction(
				"glUniform1fv", failures));
	uniform2fv = reinterpret_cast<Uniform2fvFunc *>(_loadFunction(
				"glUniform2fv", failures));
	uniform3fv = reinterpret_cast<Uniform3fvFunc *>(_loadFunction(
				"glUniform3fv", failures));
	uniform4fv = reinterpret_cast<Uniform4fvFunc *>(_loadFunction(
				"glUniform4fv", failures));
	uniform1iv = reinterpret_cast<Uniform1ivFunc *>(_loadFunction(
				"glUniform1iv", failures));
	uniform2iv = reinterpret_cast<Uniform2ivFunc *>(_loadFunction(
				"glUniform2iv", failures));
	uniform3iv = reinterpret_cast<Uniform3ivFunc *>(_loadFunction(
				"glUniform3iv", failures));
	uniform4iv = reinterpret_cast<Uniform4ivFunc *>(_loadFunction(
				"glUniform4iv", failures));
	uniformMatrix2fv = 
		reinterpret_cast<UniformMatrix2fvFunc *>(_loadFunction(
					"glUniformMatrix2fv", failures));
	uniformMatrix3fv = 
		reinterpret_cast<UniformMatrix3fvFunc *>(_loadFunction(
					"glUniformMatrix3fv", failures));
	uniformMatrix4fv = 
		reinterpret_cast<UniformMatrix4fvFunc *>(_loadFunction(
					"glUniformMatrix4fv", failures));

	genTextures = reinterpret_cast<GenTexturesFunc *>(_loadFunction(
				"glGenTextures", failures));
	deleteTextures = reinterpret_cast<DeleteTexturesFunc *>(_loadFunction(
				"glDeleteTextures", failures));
	bindTexture = reinterpret_cast<BindTextureFunc *>(_loadFunction(
				"glBindTexture", failures));
	texImage2D = reinterpret_cast<TexImage2DFunc *>(_loadFunction(
				"glTexImage2D", failures));
	texParameterf = reinterpret_cast<TexParameterfFunc *>(_loadFunction(
				"glTexParameterf", failures));
	texParameteri = reinterpret_cast<TexParameteriFunc *>(_loadFunction(
				"glTexParameteri", failures));
	texParameterfv = reinterpret_cast<TexParameterfvFunc *>(_loadFunction(
				"glTexParameterfv", failures));
	texParameteriv = reinterpret_cast<TexParameterivFunc *>(_loadFunction(
				"glTexParameteriv", failures));
	activeTexture = reinterpret_cast<ActiveTextureFunc *>(_loadFunction(
				"glActiveTexture", failures));

	genFramebuffers = reinterpret_cast<GenFramebuffersFunc *>(_loadFunction(
				"glGenFramebuffers", failures));
	deleteFramebuffers = 
		reinterpret_cast<DeleteFramebuffersFunc *>(_loadFunction(
					"glDeleteFramebuffers", failures));
	bindFramebuffer = reinterpret_cast<BindFramebufferFunc *>(_loadFunction(
				"glBindFramebuffer", failures));
	framebufferTexture2D = 
		reinterpret_cast<FramebufferTexture2DFunc *>(_loadFunction(
					"glFramebufferTexture2D", failures));
	checkFramebufferStatus = 
		reinterpret_cast<CheckFramebufferStatusFunc *>(_loadFunction(
					"glCheckFramebufferStatus", failures));
	readPixels = 
		reinterpret_cast<ReadPixelsFunc *>(_loadFunction(
					"glReadPixels", failures));

	frontFace = reinterpret_cast<FrontFaceFunc *>(_loadFunction(
				"glFrontFace", failures));
	cullFace = reinterpret_cast<CullFaceFunc *>(_loadFunction(
				"glCullFace", failures));
	enable = reinterpret_cast<EnableFunc *>(_loadFunction(
				"glEnable", failures));
	disable = reinterpret_cast<DisableFunc *>(_loadFunction(
				"glDisable", failures));


	/* FIXME: Add more */

	if (failures.size()) {
		std::string failuresStr = failures[0];
		for (size_t fIndex = 1; fIndex < failures.size(); fIndex++) {
			failuresStr += std::string(" ") + failures[fIndex];
		}

		EPRINTF("", "Failed to load GL functions:\n%s\n", 
				failuresStr.c_str());
		exit(1);
	}
}


/* One more global variable */

ATD::Gl ATD::gl;


